import React, { useState, useMemo } from 'react';
import {
  Maximize2,
  Sun,
  Zap,
  Gauge,
  Sliders,
  Sparkles,
  Activity,
  Layers,
  CheckCircle2,
  Lightbulb,
} from 'lucide-react';
import becquerelPhoto from '../../../assets/renewable/becquerel_photovoltaic_effect_1839.jpg';
import { HiResImageModal, type HiResImageModalData } from '../christian/HiResImageModal';

interface Props {
  isArabic: boolean;
  isLight?: boolean;
  isContrast?: boolean;
}

interface Hotspot {
  id: string;
  x: number;
  y: number;
  titleAr: string;
  titleEn: string;
  categoryAr: string;
  categoryEn: string;
  descAr: string;
  descEn: string;
  photovoltaicInsightAr: string;
  photovoltaicInsightEn: string;
}

export const BECQUEREL_1839_HOTSPOTS: Hotspot[] = [
  {
    id: 'illuminated_silver_chloride_electrodes',
    x: 48,
    y: 36,
    titleAr: 'أقطاب البلاتين المغلفة بهاليد الفضة المضاءة شمسياً',
    titleEn: 'Illuminated Silver Halide Coated Platinum Electrodes',
    categoryAr: 'التوليد الكهروضوئي',
    categoryEn: 'Photovoltaic Junction',
    descAr:
      'زوج من أقطاب البلاتين الدقيقة، أحدهما مغلف بغشاء رقيق من كلوريد الفضة (AgCl) أو بروميد الفضة، منغمسين في محلول حمضي. عند تسليط ضوء الشمس على أحد القطبين مع حجب الآخر، تتولد شحنات حرة وفرق جهد كهربي فوري.',
    descEn:
      'A matched pair of delicate platinum electrodes, one coated with a thin film of photosensitive silver chloride (AgCl) or silver bromide, immersed in acidic solution. Illumination of one electrode creates photo-generated charge carriers and an instantaneous potential difference.',
    photovoltaicInsightAr:
      'أول رصد تاريخي مسجل لظاهرة تحويل الفوتونات الضوئية مباشرة إلى تيار كهربائي (Photovoltaic Effect) في التاريخ العلمي.',
    photovoltaicInsightEn:
      'The first historically documented observation of the direct conversion of light photons into electrical current (Photovoltaic Effect).',
  },
  {
    id: 'three_phase_electrochemical_cell',
    x: 52,
    y: 54,
    titleAr: 'الخلية الكهروضوئية السائلة وحوض المحلول الحمضي',
    titleEn: 'Electrochemical Photocell Vessel & Electrolyte',
    categoryAr: 'الوصلة الكهروضوئية السائلة',
    categoryEn: 'Semiconductor-Liquid Junction',
    descAr:
      'وعاء زجاجي شفاف يحوي محلولاً إلكتروليتياً مخففاً من حمض النيتريك أو الكبريتيك، يشكل وصلة كهروكيميائية سائلة بين شبه الموصل (هاليد الفضة) والمحلول، حيث يفصل الحقل الكهربائي الداخلي الإلكترونات عن الثقوب الموجبة.',
    descEn:
      'A transparent glass cell containing dilute nitric or sulfuric acid electrolyte, establishing a semiconductor-liquid junction where the built-in electric field separates photo-excited electron-hole pairs before recombination.',
    photovoltaicInsightAr:
      'يمثل هذا الوعاء الزجاجي البسيط الجد الأكبر للوصلات الثنائية الحديثة (p-n Junction) وخلايا السيليكون الشمسية الصلبة.',
    photovoltaicInsightEn:
      'This modest glass cell is the direct physical ancestor of modern solid-state semiconductor p-n junctions and silicon solar wafers.',
  },
  {
    id: 'nobili_astatic_galvanometer',
    x: 22,
    y: 45,
    titleAr: 'جلفانوميتر نوبيلي الاستاتيكي فائق الحساسية',
    titleEn: 'Nobili Astatic Reflecting Galvanometer',
    categoryAr: 'القياس الكهروضوئي الدقيق',
    categoryEn: 'Precision Galvanometry',
    descAr:
      'جلفانوميتر استاتيكي متطور بإبرتين مغناطيسيتين متضادتين ملفوفتين بأسلاك حريرية نحاسية رفيعة ومرآة عاكسة، قادر على رصد أجزاء الميكروأمبير الناتجة عن إضاءة الخلية الشمسية البسيطة بدقة متناهية.',
    descEn:
      'A precision Nobili astatic galvanometer featuring twin opposing magnetic needles suspended by silk thread with a miniature reflecting mirror, capable of detecting the microampere photocurrents generated by Becquerel’s primitive photocell.',
    photovoltaicInsightAr:
      'أثبت انحراف الإبرة اللحظي مع كل ومضة ضوء أن الكهرباء المتولدة ليست ناتجة عن حرارة عادية، بل عن تفاعل مباشر مع الضوء نفسه.',
    photovoltaicInsightEn:
      'The instantaneous needle deflection with each beam of light proved the current was not thermal in origin, but a pure photoelectric phenomenon.',
  },
  {
    id: 'optical_prisms_spectral_filters',
    x: 75,
    y: 62,
    titleAr: 'المنشور الزجاجي والفلاتر اللونية للتحليل الطيفي',
    titleEn: 'Glass Optical Prism & Spectral Color Filters',
    categoryAr: 'الفيزياء الطيفية للفوتونات',
    categoryEn: 'Spectral Photon Physics',
    descAr:
      'منشور زجاجي بصري وفلاتر لونية من الزجاج الأزرق والأحمر استخدمها بيكريل لتحليل ضوء الشمس إلى ألوان الطيف، مكتشفاً أن الأشعة فوق البنفسجية والزرقاء تولد تياراً أعلى بكثير من الأشعة الحمراء.',
    descEn:
      'A high-index glass prism and colored transmission filters used by Becquerel to decompose sunlight across the spectrum, proving that violet and ultraviolet wavelengths produced far higher photocurrents than red wavelengths.',
    photovoltaicInsightAr:
      'كشف هذا الاكتشاف التجريبي عن الطبيعة الكمية للفوتونات قبل آينشتاين وماكس بلانك بنصف قرن: طاقة الفوتون E = hc / λ تتناسب عكسياً مع الطول الموجي.',
    photovoltaicInsightEn:
      'This anticipated quantum photon physics half a century before Planck and Einstein: photon energy E = hc / λ is inversely proportional to wavelength.',
  },
  {
    id: 'academie_des_sciences_memoire_1839',
    x: 68,
    y: 78,
    titleAr: 'مجلد أكاديمية العلوم بباريس (مذكرات ۱۸۳۹)',
    titleEn: '1839 French Academy of Sciences Master Folio',
    categoryAr: 'التوثيق العلمي الأصيل',
    categoryEn: 'Archival Scientific Record',
    descAr:
      'المجلد التأسيسي الأصلي من "Comptes Rendus de l’Académie des Sciences" لعام 1839 مفتوحاً على بحث إدموند بيكريل بعنوان "Mémoire sur les effets électriques produits sous l’influence des rayons solaires"، مدوناً بخط اليد مع رسومات تجاربه.',
    descEn:
      'The foundational 1839 folio of the French Academy of Sciences open to 19-year-old Alexandre-Edmond Becquerel’s paper "Memoir on electric effects produced under the influence of solar rays", recording his initial measurements.',
    photovoltaicInsightAr:
      'كان إدموند بيكريل في التاسعة عشرة من عمره فقط حين قدم بحثه للأكاديمية، واضعاً حجر الأساس لصناعة الطاقة الكهروضوئية التي تضيء مدن الأرض اليوم.',
    photovoltaicInsightEn:
      'Edmond Becquerel was only 19 years old when presenting this paper, laying the empirical cornerstone for today’s terawatt-scale solar PV industry.',
  },
];

export const BecquerelPhotovoltaicStudio: React.FC<Props> = ({
  isArabic,
  isLight = false,
  isContrast = false,
}) => {
  const [selectedHotspot, setSelectedHotspot] = useState<Hotspot>(BECQUEREL_1839_HOTSPOTS[0]);
  const [showHiResModal, setShowHiResModal] = useState<boolean>(false);

  // Simulator Inputs
  const [wavelengthNm, setWavelengthNm] = useState<number>(400); // incident wavelength nm
  const [bandgapEv, setBandgapEv] = useState<number>(1.12); // semiconductor bandgap (1.12 eV Silicon, 1.42 GaAs, 3.2 AgCl)
  const [irradianceWm2, setIrradianceWm2] = useState<number>(900); // Solar Irradiance W/m² (Benban Egypt)
  const [cellAreaCm2, setCellAreaCm2] = useState<number>(244); // 244 cm² (M10 standard silicon wafer)
  const [temperatureC, setTemperatureC] = useState<number>(25); // Cell temperature °C

  // Photovoltaic Calculations
  const metrics = useMemo(() => {
    // Photon energy: E (eV) = 1239.84 / lambda(nm)
    const photonEnergyEv = 1239.84 / Math.max(100, wavelengthNm);
    const cutoffWavelengthNm = 1239.84 / bandgapEv;

    // Check if photon has sufficient energy to overcome bandgap
    const isAbsorbed = photonEnergyEv >= bandgapEv;

    // Quantum efficiency estimation
    let internalQe = 0;
    if (isAbsorbed) {
      // Peak near bandgap, slight decay in deep UV due to surface recombination
      internalQe = Math.min(0.95, 0.5 + 0.45 * (1 - Math.abs(photonEnergyEv - bandgapEv * 1.3) / 3));
    }

    // Thermal voltage: V_th = k * T / q
    const tempK = temperatureC + 273.15;
    const vTh = (1.380649e-23 * tempK) / 1.60217663e-19; // ~0.0257 V at 25°C

    // Photocurrent generation (A)
    // Irradiance G (W/m²), Area A (m² = cm² / 10000)
    const areaM2 = cellAreaCm2 / 10000;
    const incidentLightPowerW = irradianceWm2 * areaM2;

    // Ideal short-circuit current Isc
    // For standard silicon: ~40 mA/cm² at 1000 W/m²
    const baseJscAcm2 = 0.040 * (irradianceWm2 / 1000) * (isAbsorbed ? internalQe : 0.02);
    const iscAmps = baseJscAcm2 * cellAreaCm2;

    // Open circuit voltage Voc: Voc = Vth * ln(Isc / I0 + 1)
    // Dark saturation current I0 ~ 1e-12 A * cm² * exp(-Eg / kT)
    const vocVolts = isAbsorbed
      ? Math.min(0.82, Math.max(0.05, (bandgapEv * 0.68) - (temperatureC - 25) * 0.0021))
      : 0.02;

    // Fill Factor FF
    const ff = isAbsorbed ? 0.81 : 0.40;

    // Maximum power output (W)
    const pMaxW = vocVolts * iscAmps * ff;

    // Photovoltaic conversion efficiency (%)
    const efficiencyPct = incidentLightPowerW > 0 ? (pMaxW / incidentLightPowerW) * 100 : 0;

    return {
      photonEnergyEv: Number(photonEnergyEv.toFixed(3)),
      cutoffWavelengthNm: Math.round(cutoffWavelengthNm),
      isAbsorbed,
      internalQePct: Math.round(internalQe * 100),
      incidentLightPowerW: Number(incidentLightPowerW.toFixed(2)),
      iscAmps: Number(iscAmps.toFixed(2)),
      vocVolts: Number(vocVolts.toFixed(3)),
      vThMv: Number((vTh * 1000).toFixed(1)),
      ffPct: Number((ff * 100).toFixed(1)),
      pMaxW: Number(pMaxW.toFixed(2)),
      efficiencyPct: Number(efficiencyPct.toFixed(1)),
    };
  }, [wavelengthNm, bandgapEv, irradianceWm2, cellAreaCm2, temperatureC]);

  const modalData: HiResImageModalData = {
    imageUrl: becquerelPhoto,
    titleAr: 'معمل ألكسندر إدموند بيكريل واكتشاف الأثر الكهروضوئي (باريس ۱۸۳۹)',
    titleEn: 'Alexandre-Edmond Becquerel Photovoltaic Effect Laboratory (Paris 1839)',
    subtitleAr: 'أول تحويل مباشر لضوء الشمس إلى كهرباء وولادة علم الطاقة الشمسية الكهروضوئية',
    subtitleEn: 'The Discovery of Direct Solar-to-Electric Conversion and Birth of Photovoltaics',
    descriptionAr:
      'لوحة أرشيفية متحفية بالغة الندرة تمثل المعمل الكهروضوئي للفيزيائي الفرنسي ألكسندر إدموند بيكريل في متحف التاريخ الطبيعي بباريس عام 1839. يظهر في اللوحة الوعاء الزجاجي المحتوي على أقطاب الفضة المضاءة بشعاع الشمس المركز، وجلفانوميتر نوبيلي فائق الحساسية المنحرف، والمنشور الزجاجي البصري، إلى جانب المجلد الأصلي لمذكرات أكاديمية العلوم بباريس لعام 1839.',
    descriptionEn:
      'Museum archival plate of French physicist Alexandre-Edmond Becquerel’s 1839 laboratory at the Muséum National d’Histoire Naturelle in Paris. It depicts the glass electrochemical cell with silver halide coated electrodes illuminated by a solar beam, sensitive Nobili astatic galvanometer, optical prism, and the 1839 French Academy of Sciences master folio.',
    locationAr: 'المتحف الوطني للتاريخ الطبيعي ومعهد كونسرفتوار الفنون، باريس، فرنسا',
    locationEn: 'Muséum National d’Histoire Naturelle & CNAM Archive, Paris, France',
    dateOrEraAr: '۱۸۳۹ ميلادية (عصر تأسيس الكهروضوئيات والفيزياء البصرية)',
    dateOrEraEn: '1839 CE (Founding Era of Photovoltaics & Modern Optics)',
  };

  return (
    <div
      className={`space-y-8 p-4 md:p-6 rounded-2xl border transition-all ${
        isContrast
          ? 'bg-black text-amber-300 border-amber-400'
          : isLight
          ? 'bg-slate-50 text-slate-900 border-slate-200'
          : 'bg-slate-950 text-slate-100 border-slate-800'
      }`}
      dir={isArabic ? 'rtl' : 'ltr'}
    >
      {/* Header Banner */}
      <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-4 border-b pb-6 border-amber-500/20">
        <div>
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full text-xs font-semibold bg-amber-500/10 text-amber-400 border border-amber-500/20 mb-2">
            <Sun className="w-3.5 h-3.5" />
            <span>{isArabic ? 'مكتشف الأثر الكهروضوئي (۱۸۳۹)' : 'Discoverer of the Photovoltaic Effect (1839)'}</span>
          </div>
          <h2 className="text-2xl md:text-3xl font-bold tracking-tight">
            {isArabic ? 'استوديو ألكسندر إدموند بيكريل والأثر الكهروضوئي (۱۸۳۹)' : 'Alexandre-Edmond Becquerel Photovoltaic Studio'}
          </h2>
          <p className="text-sm opacity-80 mt-1 max-w-3xl">
            {isArabic
              ? 'دراسة فيزيائية لطاقة الفوتونات وفجوة نطاق أشباه الموصلات ومنحنيات التيار-الجهد (I-V) للخلايا الشمسية.'
              : 'Physical and quantum investigation of photon energies, semiconductor bandgap excitation, and solar cell I-V kinetics.'}
          </p>
        </div>

        <button
          onClick={() => setShowHiResModal(true)}
          className="min-h-[44px] min-w-[44px] px-4 py-2.5 rounded-xl font-medium flex items-center gap-2 bg-gradient-to-r from-amber-600 to-orange-600 text-white shadow-lg hover:brightness-110 active:scale-95 transition-all text-sm"
        >
          <Maximize2 className="w-4 h-4" />
          <span>{isArabic ? 'استعراض اللوحة بدقة 4K' : 'View 4K Archival Plate'}</span>
        </button>
      </div>

      {/* Main Archival Canvas with Hotspots */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        <div className="lg:col-span-8 space-y-4">
          <div className="relative rounded-2xl overflow-hidden border border-amber-500/30 shadow-2xl bg-black aspect-[4/3] group">
            <img
              src={becquerelPhoto}
              alt="Alexandre-Edmond Becquerel 1839 Laboratory"
              className="w-full h-full object-cover select-none"
            />
            <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-black/30 pointer-events-none" />

            {/* Hotspot Markers */}
            {BECQUEREL_1839_HOTSPOTS.map((spot) => {
              const isSelected = selectedHotspot.id === spot.id;
              return (
                <button
                  key={spot.id}
                  onClick={() => setSelectedHotspot(spot)}
                  style={{ left: `${spot.x}%`, top: `${spot.y}%` }}
                  aria-label={isArabic ? spot.titleAr : spot.titleEn}
                  className={`absolute -translate-x-1/2 -translate-y-1/2 min-w-[44px] min-h-[44px] flex items-center justify-center transition-all z-10 ${
                    isSelected ? 'scale-125 z-20' : 'hover:scale-110 opacity-90'
                  }`}
                >
                  <span
                    className={`relative flex items-center justify-center w-8 h-8 rounded-full border-2 transition-all ${
                      isSelected
                        ? 'bg-amber-500 border-white text-black shadow-lg shadow-amber-500/80 ring-4 ring-amber-500/40'
                        : 'bg-slate-900/90 border-amber-400 text-amber-300 backdrop-blur-sm'
                    }`}
                  >
                    <Lightbulb className="w-4 h-4" />
                  </span>
                </button>
              );
            })}

            {/* Live Overlay Caption */}
            <div className="absolute bottom-4 left-4 right-4 p-4 rounded-xl backdrop-blur-md bg-slate-900/80 border border-slate-700/60 text-xs md:text-sm">
              <span className="font-semibold text-amber-400 block mb-1">
                {isArabic ? selectedHotspot.titleAr : selectedHotspot.titleEn}
              </span>
              <p className="line-clamp-2 opacity-90">
                {isArabic ? selectedHotspot.descAr : selectedHotspot.descEn}
              </p>
            </div>
          </div>

          {/* Hotspots Selector Row */}
          <div className="grid grid-cols-2 sm:grid-cols-5 gap-2">
            {BECQUEREL_1839_HOTSPOTS.map((spot) => {
              const isSelected = selectedHotspot.id === spot.id;
              return (
                <button
                  key={spot.id}
                  onClick={() => setSelectedHotspot(spot)}
                  className={`min-h-[44px] p-2.5 rounded-xl border text-xs font-medium text-left transition-all ${
                    isArabic ? 'text-right' : 'text-left'
                  } ${
                    isSelected
                      ? 'bg-amber-500/20 border-amber-500 text-amber-400 shadow-sm'
                      : isLight
                      ? 'bg-white border-slate-200 text-slate-700 hover:bg-slate-100'
                      : 'bg-slate-900/60 border-slate-800 text-slate-300 hover:bg-slate-800/80'
                  }`}
                >
                  <span className="line-clamp-1 block font-semibold">{isArabic ? spot.titleAr : spot.titleEn}</span>
                  <span className="text-[10px] opacity-70 block">{isArabic ? spot.categoryAr : spot.categoryEn}</span>
                </button>
              );
            })}
          </div>
        </div>

        {/* Selected Hotspot Deep-Dive Inspector */}
        <div className="lg:col-span-4 space-y-4">
          <div
            className={`p-5 rounded-2xl border space-y-4 ${
              isLight ? 'bg-white border-slate-200 shadow-sm' : 'bg-slate-900/80 border-slate-800'
            }`}
          >
            <div className="flex items-center gap-2 text-amber-400">
              <Sparkles className="w-5 h-5" />
              <h3 className="font-bold text-base">
                {isArabic ? 'الملف الكهروضوئي والفيزيائي' : 'Photovoltaic Physics Dossier'}
              </h3>
            </div>

            <div>
              <span className="text-xs uppercase tracking-wider text-amber-400 font-semibold block mb-1">
                {isArabic ? selectedHotspot.categoryAr : selectedHotspot.categoryEn}
              </span>
              <h4 className="text-lg font-bold">
                {isArabic ? selectedHotspot.titleAr : selectedHotspot.titleEn}
              </h4>
            </div>

            <p className="text-sm leading-relaxed opacity-90">
              {isArabic ? selectedHotspot.descAr : selectedHotspot.descEn}
            </p>

            <div className="p-3.5 rounded-xl bg-amber-500/10 border border-amber-500/20 space-y-1.5">
              <span className="text-xs font-bold text-amber-400 flex items-center gap-1.5">
                <Gauge className="w-4 h-4" />
                {isArabic ? 'المعادلة الكهروضوئية لبيكريل (۱۸۳۹)' : 'Becquerel Photo-Electric Law'}
              </span>
              <p className="text-xs font-mono opacity-90 leading-relaxed">
                {isArabic ? selectedHotspot.photovoltaicInsightAr : selectedHotspot.photovoltaicInsightEn}
              </p>
            </div>
          </div>

          {/* Quick Photovoltaic Stats */}
          <div
            className={`p-5 rounded-2xl border grid grid-cols-2 gap-3 text-center ${
              isLight ? 'bg-white border-slate-200' : 'bg-slate-900/80 border-slate-800'
            }`}
          >
            <div className="p-3 rounded-xl bg-amber-500/10 border border-amber-500/20">
              <span className="text-xs opacity-75 block">{isArabic ? 'طاقة الفوتون E' : 'Photon Energy'}</span>
              <span className="text-lg font-bold text-amber-400 font-mono">{metrics.photonEnergyEv} eV</span>
            </div>
            <div className="p-3 rounded-xl bg-orange-500/10 border border-orange-500/20">
              <span className="text-xs opacity-75 block">{isArabic ? 'جهد الدائرة المفتوحة' : 'Open Circuit Voc'}</span>
              <span className="text-lg font-bold text-orange-400 font-mono">{metrics.vocVolts} V</span>
            </div>
            <div className="p-3 rounded-xl bg-emerald-500/10 border border-emerald-500/20">
              <span className="text-xs opacity-75 block">{isArabic ? 'كفاءة التحويل' : 'Solar Efficiency'}</span>
              <span className="text-lg font-bold text-emerald-400 font-mono">{metrics.efficiencyPct}%</span>
            </div>
            <div className="p-3 rounded-xl bg-yellow-500/10 border border-yellow-500/20">
              <span className="text-xs opacity-75 block">{isArabic ? 'القدرة القصوى Pmax' : 'Peak Power Pmax'}</span>
              <span className="text-lg font-bold text-yellow-400 font-mono">{metrics.pMaxW} W</span>
            </div>
          </div>
        </div>
      </div>

      {/* Interactive Photovoltaic & Bandgap Simulator */}
      <div
        className={`p-6 rounded-2xl border space-y-6 ${
          isLight ? 'bg-white border-slate-200 shadow-sm' : 'bg-slate-900/60 border-slate-800'
        }`}
      >
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-3 border-b border-amber-500/20 pb-4">
          <div className="flex items-center gap-3">
            <div className="p-2.5 rounded-xl bg-amber-500/10 text-amber-400 border border-amber-500/20">
              <Sliders className="w-5 h-5" />
            </div>
            <div>
              <h3 className="font-bold text-lg">
                {isArabic
                  ? 'محاكي طاقة الفوتون وفجوة النطاق ومنحنيات الخلايا الشمسية (I-V Simulator)'
                  : 'Photon Energy, Semiconductor Bandgap & Solar Cell I-V Simulator'}
              </h3>
              <p className="text-xs opacity-75">
                {isArabic
                  ? 'تعديل الطول الموجي للفوتون، فجوة النطاق، وشدة الإشعاع لدراسة إثارة الإلكترونات وتوليد الكهرباء'
                  : 'Modulate wavelength, semiconductor bandgap, and irradiance to analyze carrier generation and I-V curves'}
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2 text-xs font-mono bg-slate-800/80 px-3 py-1.5 rounded-lg border border-slate-700">
            <Zap className="w-4 h-4 text-amber-400" />
            <span>Cutoff λ: {metrics.cutoffWavelengthNm} nm</span>
          </div>
        </div>

        {/* Sliders Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          {/* Incident Wavelength */}
          <div className="space-y-2">
            <div className="flex justify-between text-xs">
              <span className="font-medium text-amber-400 flex items-center gap-1">
                <Sun className="w-3.5 h-3.5" />
                {isArabic ? 'الطول الموجي للضوء (λ)' : 'Incident Wavelength (λ)'}
              </span>
              <span className="font-mono font-bold">{wavelengthNm} nm</span>
            </div>
            <input
              type="range"
              min="280"
              max="1150"
              step="10"
              value={wavelengthNm}
              onChange={(e) => setWavelengthNm(Number(e.target.value))}
              className="w-full accent-amber-500 min-h-[44px]"
            />
            <div className="flex justify-between text-[10px] opacity-60">
              <span>300 nm (فوق بنفسجي)</span>
              <span>550 nm (أخضر مرئي)</span>
              <span>1100 nm (تحت أحمر)</span>
            </div>
          </div>

          {/* Semiconductor Bandgap */}
          <div className="space-y-2">
            <div className="flex justify-between text-xs">
              <span className="font-medium text-amber-400 flex items-center gap-1">
                <Layers className="w-3.5 h-3.5" />
                {isArabic ? 'فجوة النطاق (Eg)' : 'Bandgap Energy (Eg)'}
              </span>
              <span className="font-mono font-bold">{bandgapEv} eV</span>
            </div>
            <input
              type="range"
              min="0.7"
              max="3.4"
              step="0.05"
              value={bandgapEv}
              onChange={(e) => setBandgapEv(Number(e.target.value))}
              className="w-full accent-amber-500 min-h-[44px]"
            />
            <div className="flex justify-between text-[10px] opacity-60">
              <span>1.12 eV (سيليكون Si)</span>
              <span>1.42 eV (GaAs)</span>
              <span>3.2 eV (AgCl بيكريل)</span>
            </div>
          </div>

          {/* Irradiance */}
          <div className="space-y-2">
            <div className="flex justify-between text-xs">
              <span className="font-medium text-amber-400 flex items-center gap-1">
                <Sparkles className="w-3.5 h-3.5" />
                {isArabic ? 'شدة الإشعاع الشمسي (G)' : 'Solar Irradiance (G)'}
              </span>
              <span className="font-mono font-bold">{irradianceWm2} W/m²</span>
            </div>
            <input
              type="range"
              min="100"
              max="1200"
              step="50"
              value={irradianceWm2}
              onChange={(e) => setIrradianceWm2(Number(e.target.value))}
              className="w-full accent-amber-500 min-h-[44px]"
            />
            <div className="flex justify-between text-[10px] opacity-60">
              <span>100 W/m² (غائم)</span>
              <span>900 W/m² (بنبان، مصر)</span>
              <span>1200 W/m² (ذروة)</span>
            </div>
          </div>

          {/* Cell Temperature */}
          <div className="space-y-2">
            <div className="flex justify-between text-xs">
              <span className="font-medium text-amber-400 flex items-center gap-1">
                <Gauge className="w-3.5 h-3.5" />
                {isArabic ? 'حرارة الخلية الكهروضوئية' : 'Cell Operating Temp'}
              </span>
              <span className="font-mono font-bold">{temperatureC}°C</span>
            </div>
            <input
              type="range"
              min="10"
              max="70"
              step="1"
              value={temperatureC}
              onChange={(e) => setTemperatureC(Number(e.target.value))}
              className="w-full accent-amber-500 min-h-[44px]"
            />
            <div className="flex justify-between text-[10px] opacity-60">
              <span>10°C (شتاء مشمس)</span>
              <span>25°C (قياس STC)</span>
              <span>70°C (صيف صحراوي)</span>
            </div>
          </div>

          {/* Cell Surface Area */}
          <div className="space-y-2">
            <div className="flex justify-between text-xs">
              <span className="font-medium text-amber-400 flex items-center gap-1">
                <Layers className="w-3.5 h-3.5" />
                {isArabic ? 'مساحة سطح الخلية' : 'Cell Surface Area'}
              </span>
              <span className="font-mono font-bold">{cellAreaCm2} cm²</span>
            </div>
            <input
              type="range"
              min="20"
              max="400"
              step="10"
              value={cellAreaCm2}
              onChange={(e) => setCellAreaCm2(Number(e.target.value))}
              className="w-full accent-amber-500 min-h-[44px]"
            />
            <div className="flex justify-between text-[10px] opacity-60">
              <span>20 cm² (خلية بيضاوية 1839)</span>
              <span>244 cm² (رقاقة M10 حديثة)</span>
              <span>400 cm² (شريحة عريضة M12)</span>
            </div>
          </div>
        </div>

        {/* Vector SVG Diagram of Solar Cell I-V and P-V Characteristics */}
        <div className="p-4 rounded-xl bg-slate-950 border border-slate-800 space-y-4">
          <div className="flex items-center justify-between text-xs text-slate-400">
            <span className="flex items-center gap-1 font-semibold text-amber-400">
              <Activity className="w-3.5 h-3.5" />
              {isArabic
                ? 'منحنيات تيار-جهد (I-V) والقدرة (P-V) ونقطة القدرة العظمى (MPPT)'
                : 'Solar Cell I-V & P-V Curves with Maximum Power Point (MPP)'}
            </span>
            <span className="text-emerald-400 font-mono">P_max: {metrics.pMaxW} W</span>
          </div>

          <div className="w-full aspect-[21/9] max-h-56 relative flex items-center justify-center overflow-hidden">
            <svg viewBox="0 0 800 240" className="w-full h-full">
              {/* Axes */}
              <line x1="60" y1="200" x2="740" y2="200" stroke="#64748b" strokeWidth="1.5" />
              <line x1="60" y1="200" x2="60" y2="30" stroke="#64748b" strokeWidth="1.5" />

              {/* I-V Curve: Constant current up to knee, then sharp drop to Voc */}
              <path
                d="M 60 60 L 520 60 C 580 60, 620 90, 640 200"
                fill="none"
                stroke="#38bdf8"
                strokeWidth="3"
              />

              {/* P-V Curve (Power): Parabolic shape peaking at MPP */}
              <path
                d="M 60 200 Q 520 200, 540 85 Q 560 200, 640 200"
                fill="none"
                stroke="#10b981"
                strokeWidth="2.5"
                strokeDasharray="4 2"
              />

              {/* Maximum Power Point (MPP) Marker */}
              <circle cx="540" cy="85" r="7" fill="#f59e0b" stroke="#fff" strokeWidth="2" />
              <text x="540" y="70" textAnchor="middle" fill="#f59e0b" fontSize="10" fontWeight="bold">
                MPP ({metrics.pMaxW} W)
              </text>

              {/* Labels on Axes */}
              <text x="60" y="215" fill="#94a3b8" fontSize="10">0.0 V</text>
              <text x="380" y="225" fill="#94a3b8" fontSize="11" textAnchor="middle">Voltage V (Volts)</text>
              <text x="640" y="215" fill="#38bdf8" fontSize="10">Voc = {metrics.vocVolts} V</text>

              <text x="20" y="65" fill="#38bdf8" fontSize="10">Isc</text>
              <text x="20" y="130" fill="#94a3b8" fontSize="10">Current</text>
              <text x="20" y="200" fill="#94a3b8" fontSize="10">0 A</text>

              {/* Absorption Status Indicator */}
              <rect
                x="640"
                y="35"
                width="120"
                height="28"
                rx="6"
                fill={metrics.isAbsorbed ? '#065f46' : '#991b1b'}
              />
              <text x="700" y="52" textAnchor="middle" fill="#fff" fontSize="10" fontWeight="bold">
                {metrics.isAbsorbed ? 'E_photon ≥ Eg (امتصاص)' : 'E_photon < Eg (نفاذ)'}
              </text>
            </svg>
          </div>
          <div className="flex justify-between text-[11px] text-slate-400">
            <span>تيار القصر: I_sc = {metrics.iscAmps} A</span>
            <span>جهد الدارة المفتوحة: V_oc = {metrics.vocVolts} V</span>
            <span>معامل الامتلاء: FF = {metrics.ffPct}%</span>
            <span className="text-amber-400 font-bold">الكفاءة الكهروضوئية: η = {metrics.efficiencyPct}%</span>
          </div>
        </div>

        {/* Live Calculation Outcomes Cards */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          <div className="p-4 rounded-xl border border-amber-500/20 bg-amber-500/5 space-y-1">
            <span className="text-xs text-amber-400 font-medium block">
              {isArabic ? 'طاقة الفوتون الساقط' : 'Incident Photon Energy'}
            </span>
            <span className="text-xl font-bold font-mono text-amber-300">
              {metrics.photonEnergyEv} eV
            </span>
            <span className="text-[10px] opacity-60 block">E = hc / λ</span>
          </div>

          <div className="p-4 rounded-xl border border-orange-500/20 bg-orange-500/5 space-y-1">
            <span className="text-xs text-orange-400 font-medium block">
              {isArabic ? 'تيار القصر الكهروضوئي' : 'Short-Circuit Current'}
            </span>
            <span className="text-xl font-bold font-mono text-orange-300">
              {metrics.iscAmps} A
            </span>
            <span className="text-[10px] opacity-60 block">I_sc ∝ G · Area</span>
          </div>

          <div className="p-4 rounded-xl border border-yellow-500/20 bg-yellow-500/5 space-y-1">
            <span className="text-xs text-yellow-400 font-medium block">
              {isArabic ? 'القدرة القصوى للخلية' : 'Peak Power Output'}
            </span>
            <span className="text-xl font-bold font-mono text-yellow-300">
              {metrics.pMaxW} W
            </span>
            <span className="text-[10px] opacity-60 block">P_max = Voc · Isc · FF</span>
          </div>

          <div className="p-4 rounded-xl border border-emerald-500/20 bg-emerald-500/5 space-y-1">
            <span className="text-xs text-emerald-400 font-medium block">
              {isArabic ? 'كفاءة تحويل الخلية' : 'Conversion Efficiency'}
            </span>
            <span className="text-xl font-bold font-mono text-emerald-300">
              {metrics.efficiencyPct}%
            </span>
            <span className="text-[10px] opacity-60 block">Benban TOPCon: ~22.5%</span>
          </div>
        </div>

        {/* Historical Context Callout */}
        <div className="p-4 rounded-xl bg-amber-500/10 border border-amber-500/30 flex items-start gap-3 text-xs md:text-sm">
          <CheckCircle2 className="w-5 h-5 text-amber-400 shrink-0 mt-0.5" />
          <div className="space-y-1">
            <span className="font-bold text-amber-300">
              {isArabic ? 'من تجربة بيكريل ۱۸۳۹ إلى مجمع بنبان للطاقة الشمسية بأسوان في مصر:' : 'From Becquerel’s 1839 Cell to Egypt Benban Solar Park (Aswan):'}
            </span>
            <p className="opacity-90 leading-relaxed text-xs">
              {isArabic
                ? 'يعد مجمع بنبان للطاقة الشمسية في محافظة أسوان جنوب مصر رابع أكبر محطة توليد شمسية كهروضوئية في العالم بقدرة إجمالية تبلغ ۱.۸ جيجاوات وتضم أكثر من ٦ ملايين لوح كهروضوئي، مجسداً التحول الملحمي من خلية بيكريل المعملية ذات الكفاءة الأقل من ۱% إلى بنية تحتية وطنية عملاقة توفر الكهرباء النظيفة لملايين المنازل وتخفض مليوني طن من انبعاثات الكربون سنوياً.'
                : 'The Benban Solar Park in Aswan, southern Egypt, is the 4th largest photovoltaic installation on Earth with 1.8 GW total capacity and over 6 million solar modules. It exemplifies the monumental journey from Becquerel’s <1% laboratory cell into massive utility infrastructure powering millions of homes while averting 2 million tons of carbon emissions annually.'}
            </p>
          </div>
        </div>
      </div>

      {/* 4K Modal */}
      <HiResImageModal
        isOpen={showHiResModal}
        onClose={() => setShowHiResModal(false)}
        data={modalData}
        lang={isArabic ? 'ar' : 'en'}
        theme={isContrast ? 'high-contrast' : isLight ? 'light' : 'dark'}
      />
    </div>
  );
};
