import type { SolvedProblem } from '../../../types/curriculum';

export const egBacPhysCh3SolvedExamples: SolvedProblem[] = [
  {
    "id": "egbac_phys_ch3_se_01",
    "titleEn": "Spontaneous vs Stimulated Emission Characteristics",
    "titleAr": "خصائص الانبعاث التلقائي ومقارنته بالانبعاث المستحث",
    "difficulty": "easy",
    "questionEn": "In atomic physics, how does a photon generated by stimulated emission compare to the incident stimulating photon in terms of frequency, phase, direction, and polarization?",
    "questionAr": "في الفيزياء الذرية، كيف يقارَن الفوتون الناتج عن الانبعاث المستحث بالفوتون الساقط الحاث من حيث التردد والطور والاتجاه والاستقطاب؟",
    "optionsEn": [
      "It is completely identical in frequency, phase, propagation direction, and state of polarization.",
      "It has the same frequency but random phase and propagating in an arbitrary direction.",
      "It has double the frequency and opposite phase direction.",
      "It has half the frequency and perpendicular polarization."
    ],
    "optionsAr": [
      "مطابق له تماماً في التردد والطور واتجاه الانتشار وحالة الاستقطاب (مترابطان تماماً).",
      "له نفس التردد ولكن بطور عشوائي وينتشر في اتجاه عشوائي غير محدد.",
      "له ضعف التردد وبطور معاكس تماماً.",
      "له نصف التردد ومستقطب في اتجاه عمودي."
    ],
    "correctAnswer": "It is completely identical in frequency, phase, propagation direction, and state of polarization.",
    "correctIndex": 0,
    "hintEn": "Stimulated emission produces an identical twin photon with exact coherence.",
    "hintAr": "الانبعاث المستحث ينتج فوتوناً توأماً مطابقاً تماماً للفوتون الحاث وله نفس الطور والتردد والاتجاه.",
    "stepByStepSolutionEn": [
      "1. In spontaneous emission, excited atoms decay randomly after their lifetime, emitting incoherent photons with random directions and phases.",
      "2. In stimulated emission, an incident photon of energy $h\\nu = E_2 - E_1$ stimulates an excited electron to drop before its natural lifetime ends.",
      "3. The emitted photon is in exact phase coherence, has identical frequency $h\\nu$, travels in the exact same direction, and shares identical polarization."
    ],
    "stepByStepSolutionAr": [
      "١. في الانبعاث التلقائي: تهبط الذرة المثارة بعد انتهاء فترة العمر عشوائياً فتنبعث فوتونات غير مترابطة وذات أطوار مختلفة.",
      "٢. في الانبعاث المستحث: يحث فوتون ساقط طاقته $h\\nu = E_2 - E_1$ الذرة على الهبوط قبل انتهاء فترة عمرها.",
      "٣. الفوتون المنبعث يكون متفقاً تماماً في الطور والتردد والاتجاه والاستقطاب مع الفوتون الحاث."
    ],
    "teacherTipEn": "This identical quantum coherence is the fundamental physical basis of laser amplification.",
    "teacherTipAr": "هذا التطابق والترابط الكمي التام هو الأساس الفيزيائي لتضخيم الضوء بالليزر."
  },
  {
    "id": "egbac_phys_ch3_se_02",
    "titleEn": "Condition for Population Inversion and Metastable States",
    "titleAr": "شرط الإسكان المعكوس وحالة شبه الاستقرار",
    "difficulty": "medium",
    "questionEn": "Under normal thermal equilibrium at temperature $T$, the Boltzmann distribution requires $N_2 < N_1$. For laser action to predominate over absorption, the condition of population inversion must be established. What does population inversion mean, and what role does a metastable state play?",
    "questionAr": "في حالة الاتزان الحراري العادي عند درجة حرارة $T$، يفرض توزيع بولتزمان أن $N_2 < N_1$. لكي يغلب الانبعاث المستحث على الامتصاص، يجب تحقيق حالة الإسكان المعكوس. ما المقصود بالإسكان المعكوس، وما دور مستوى شبه الاستقرار في تحقيقه؟",
    "optionsEn": [
      "Population inversion means all electrons leave the atom; metastable state causes instantaneous ionization.",
      "Population inversion means $N_2 > N_1$; the metastable state has a long lifetime ($10^{-3}\\text{ s}$) enabling atom accumulation.",
      "Population inversion means $N_1 > N_2$; metastable state has a short lifetime ($10^{-12}\\text{ s}$).",
      "Population inversion means temperature reaches absolute zero; metastable state stores zero energy."
    ],
    "optionsAr": [
      "الإسكان المعكوس يعني مغادرة جميع الإلكترونات للذرة؛ ومستوى شبه الاستقرار يسبب تأيناً فورياً.",
      "الإسكان المعكوس يعني $N_2 > N_1$؛ ومستوى شبه الاستقرار له فترة عمر طويلة ($10^{-3}\\text{ ث}$) تسمح بتراكم الذرات.",
      "الإسكان المعكوس يعني $N_1 > N_2$؛ ومستوى شبه الاستقرار له فترة عمر قصيرة جداً ($10^{-12}\\text{ ث}$).",
      "الإسكان المعكوس يعني وصول درجة الحرارة للصفر المطلق؛ ومستوى شبه الاستقرار لا يخزن طاقة."
    ],
    "correctAnswer": "Population inversion means $N_2 > N_1$; the metastable state has a long lifetime ($10^{-3}\\text{ s}$) enabling atom accumulation.",
    "correctIndex": 1,
    "hintEn": "Normal state has N1 > N2. Inversion means excited state population N2 exceeds lower state population N1.",
    "hintAr": "في الحالة العادية N1 > N2. الإسكان المعكوس يعني أن عدد الذرات في المستوى المثار N2 يتجاوز عددها في المستوى الأدنى N1.",
    "stepByStepSolutionEn": [
      "1. By Boltzmann's law, in thermal equilibrium: $\\frac{N_2}{N_1} = e^{-\\frac{E_2 - E_1}{k_B T}} < 1 \\implies N_1 > N_2$.",
      "2. For stimulated emission to exceed stimulated absorption, the higher energy level must have a greater population than the lower level ($N_2 > N_1$), a non-equilibrium state called **population inversion**.",
      "3. Achieving this requires a **metastable level** with a relatively long lifetime (typically $\\sim 10^{-3}\\text{ s}$, compared to $\\sim 10^{-8}\\text{ s}$ for ordinary levels), allowing atoms to accumulate faster than they decay."
    ],
    "stepByStepSolutionAr": [
      "١. وفق توزيع بولتزمان في الاتزان الحراري: تكون الذرات في المستوى الأدنى أكثر عدداً دائماً ($N_1 > N_2$).",
      "٢. لكي يتغلب الانبعاث المستحث على الامتصاص، يجب جعل عدد الذرات في مستوى الإثارة أكبر من عددها في المستوى الأرضي ($N_2 > N_1$) وهو ما يُسمى **الإسكان المعكوس**.",
      "٣. لا يتحقق ذلك إلا بوجود **مستوى شبه مستقر** يتميز بفترة عمر طويلة نسبياً (حوالي $10^{-3}\\text{ ثانية}$ مقارنة بـ $10^{-8}\\text{ ثانية}$ للمستويات العادية) مما يتيح للذرات التراكم فيه."
    ],
    "teacherTipEn": "Without a metastable state, excited atoms would drop almost instantly, making population inversion impossible to sustain.",
    "teacherTipAr": "لولا مستوى شبه الاستقرار لهبطت الذرات فور إثارتها واستحال تحقيق حالة الإسكان المعكوس."
  },
  {
    "id": "egbac_phys_ch3_se_03",
    "titleEn": "Resonant Inelastic Collision Transfer in the Helium-Neon Laser",
    "titleAr": "آلية انتقال الطاقة بالرنين والتصادم غير المرن في ليزر الهيليوم - نيون",
    "difficulty": "medium",
    "questionEn": "In a Helium-Neon (He-Ne) gas laser, what is the exact function of the helium atoms, and why does the gas mixture contain approximately $10$ times more helium than neon ($10:1$ ratio)?",
    "questionAr": "في ليزر الهيليوم - نيون الغازي، ما الوظيفة الدقيقة لذرات الهيليوم، ولماذا يحتوي الخليط الغازي على نسبة من الهيليوم تبلغ حوالي عشرة أمثال النيون ($1:10$)؟",
    "optionsEn": [
      "Helium atoms directly emit the red laser beam; neon atoms only act as a chemical coolant.",
      "Helium absorbs stray photons to prevent cavity overheating; neon provides electrical conductivity.",
      "Helium atoms are easily excited by electrical discharge, then transfer energy to neon atoms via resonant inelastic collisions.",
      "Helium prevents chemical oxidation of the optical glass tube; neon is the resonant cavity reflector."
    ],
    "optionsAr": [
      "ذرات الهيليوم هي التي تشع الليزر الأحمر مباشرة؛ وذرات النيون مجرد مبرد كيميائي.",
      "يمتص الهيليوم الفوتونات الشاردة لمنع السخونة؛ والنيون يوفر التوصيل الكهربي فقط.",
      "تُثار ذرات الهيليوم بسهولة بالتفريغ الكهربي ثم تنقل طاقتها لذرات النيون بالتصادم الرنيني غير المرن لتقارب طاقتي مستوييهما شبه المستقرين.",
      "يمنع الهيليوم أكسدة الأنبوب الزجاجي؛ والنيون يمثل عاكس التجويف الرنيني."
    ],
    "correctAnswer": "Helium atoms are easily excited by electrical discharge, then transfer energy to neon atoms via resonant inelastic collisions.",
    "correctIndex": 2,
    "hintEn": "Helium's metastable level (20.66 eV) is exceptionally close to Neon's metastable level (20.61 eV).",
    "hintAr": "مستوى شبه الاستقرار للهيليوم (20.66 إلكترون فولت) متقارب جداً مع مستوى شبه الاستقرار للنيون (20.61 إلكترون فولت).",
    "stepByStepSolutionEn": [
      "1. High-voltage electrical discharge excites helium atoms by electron impact from their ground state to the long-lived metastable state $2^1S_0$ ($E = 20.66\\text{ eV}$).",
      "2. Because the $3s_2$ level of neon ($E = 20.61\\text{ eV}$) has nearly identical energy ($\\Delta E = 0.05\\text{ eV}$), excited helium atoms transfer excitation energy to unexcited neon atoms through resonant inelastic collisions: $\\text{He}^* + \\text{Ne} \\to \\text{He} + \\text{Ne}^*$.",
      "3. The 10:1 ratio ensures efficient absorption of discharge energy and rapid pumping of neon to achieve population inversion."
    ],
    "stepByStepSolutionAr": [
      "١. يُثير التفريغ الكهربي ذرات الهيليوم بالتصادم مع الإلكترونات إلى مستواها شبه المستقر ($20.66\\text{ إلكترون فولت}$).",
      "٢. لتقارب طاقتي المستويين شبه المستقرين في الهيليوم والنيون ($20.61\\text{ إلكترون فولت}$ في النيون بفارق $0.05\\text{ eV}$ فقط)، تصطدم ذرات الهيليوم المثارة بذرات نيون غير مثارة تصادماً غير مرن فتنقل إليها طاقتها بالرنين.",
      "٣. تضمن نسبة 1:10 كفاءة تفريغ عالية وسرعة ضخ لذرات النيون لتحقيق الإسكان المعكوس."
    ],
    "teacherTipEn": "The active medium that actually emits the laser photons is Neon, not Helium!",
    "teacherTipAr": "المادة الفعالة المسؤولة عن انبعاث فوتونات الليزر هي النيون وليس الهيليوم!"
  },
  {
    "id": "egbac_phys_ch3_se_04",
    "titleEn": "He-Ne Laser Wavelength & Transition Energy Gap",
    "titleAr": "الطول الموجي لليزر الهيليوم - نيون وفرق طاقة الانتقال",
    "difficulty": "easy",
    "questionEn": "The standard red emission from a Helium-Neon gas laser occurs at wavelength $\\lambda = 632.8\\text{ nm}$. Given $hc \\approx 1240\\text{ eV}\\cdot\\text{nm}$, calculate the energy difference $\\Delta E$ between the neon laser levels.",
    "questionAr": "يحدث انبعاث الضوء الأحمر القياسي في ليزر الهيليوم - نيون عند طول موجي $\\lambda = 632.8\\text{ نانومتر}$. بمعلومية $hc \\approx 1240\\text{ eV}\\cdot\\text{nm}$، احسب فرق الطاقة $\\Delta E$ بين مستويي انبعاث الليزر في ذرة النيون.",
    "optionsEn": [
      "$2.48\\text{ eV}$",
      "$1.45\\text{ eV}$",
      "$3.10\\text{ eV}$",
      "$1.96\\text{ eV}$"
    ],
    "optionsAr": [
      "$2.48\\text{ إلكترون فولت}$",
      "$1.45\\text{ إلكترون فولت}$",
      "$3.10\\text{ إلكترون فولت}$",
      "$1.96\\text{ إلكترون فولت}$"
    ],
    "correctAnswer": "$1.96\\text{ eV}$",
    "correctIndex": 3,
    "hintEn": "Use delta E = hc / lambda = 1240 / 632.8 in eV.",
    "hintAr": "طبق القانون delta E = hc / lambda = 1240 / 632.8 بالإلكترون فولت.",
    "stepByStepSolutionEn": [
      "1. Energy-wavelength relation: $\\Delta E = \\frac{hc}{\\lambda}$.",
      "2. Using $hc = 1240\\text{ eV}\\cdot\\text{nm}$: $\\Delta E = \\frac{1240\\text{ eV}\\cdot\\text{nm}}{632.8\\text{ nm}} \\approx 1.9595\\text{ eV} \\approx 1.96\\text{ eV}$."
    ],
    "stepByStepSolutionAr": [
      "١. علاقة الطاقة بالطول الموجي: $\\Delta E = \\frac{hc}{\\lambda}$.",
      "٢. بالتعويض: $\\Delta E = \\frac{1240}{632.8} \\approx 1.96\\text{ إلكترون فولت}$."
    ],
    "teacherTipEn": "This corresponds to the transition from Neon's 5s (in Paschen notation 3s) level to its 3p (2p) level.",
    "teacherTipAr": "يناظر هذا الانتقال هبوط إلكترون النيون من المستوى شبه المستقر إلى مستوى إثارة أدنى محرراً فوتون الضوء الأحمر."
  },
  {
    "id": "egbac_phys_ch3_se_05",
    "titleEn": "Longitudinal Cavity Mode Frequency Spacing in Fabry-Perot Resonator",
    "titleAr": "التباعد الترددي بين أنماط التجاويف الطولية في مرنان فابري - بيرو",
    "difficulty": "medium",
    "questionEn": "A Helium-Neon laser cavity has an optical length of $L = 50\\text{ cm} = 0.50\\text{ m}$ between its flat mirrors. What is the frequency separation $\\Delta\\nu$ between adjacent longitudinal cavity modes? (Given $c = 3.0 \\times 10^8\\text{ m/s}$).",
    "questionAr": "يبلغ طول التجويف الرنيني البصري لليزر هيليوم - نيون $L = 50\\text{ سم} = 0.50\\text{ م}$ بين مرآتيه المستويتين. ما التباعد الترددي $\\Delta\\nu$ بين نمطين طوليين متتاليين من أنماط التجويف؟ (بمعلومية $c = 3.0 \\times 10^8\\text{ م/ث}$).",
    "optionsEn": [
      "$300\\text{ MHz} \\; (3.0 \\times 10^8\\text{ Hz})$",
      "$150\\text{ MHz}$",
      "$600\\text{ MHz}$",
      "$100\\text{ MHz}$"
    ],
    "optionsAr": [
      "$300\\text{ ميجاهرتز} \\; (3.0 \\times 10^8\\text{ هرتز})$",
      "$150\\text{ ميجاهرتز}$",
      "$600\\text{ ميجاهرتز}$",
      "$100\\text{ ميجاهرتز}$"
    ],
    "correctAnswer": "$300\\text{ MHz} \\; (3.0 \\times 10^8\\text{ Hz})$",
    "correctIndex": 0,
    "hintEn": "Standing wave condition: L = m * (lambda / 2) = m * c / (2 * nu). Therefore, Delta nu = c / (2 * L).",
    "hintAr": "شرط الموجات الموقوفة في المرنان: L = m * (lambda / 2) = m * c / (2 * nu). ومنه التباعد الترددي Delta nu = c / (2 * L).",
    "stepByStepSolutionEn": [
      "1. Standing wave resonance condition in an optical cavity: $L = m \\frac{\\lambda}{2} = m \\frac{c}{2\\nu} \\implies \\nu_m = m \\frac{c}{2L}$.",
      "2. Frequency difference between adjacent modes ($m+1$ and $m$): $\\Delta\\nu = \\nu_{m+1} - \\nu_m = \\frac{c}{2L}$.",
      "3. Substitute $c = 3.0 \\times 10^8\\text{ m/s}$ and $L = 0.50\\text{ m}$: $\\Delta\\nu = \\frac{3.0 \\times 10^8\\text{ m/s}}{2 \\times 0.50\\text{ m}} = 3.0 \\times 10^8\\text{ Hz} = 300\\text{ MHz}$."
    ],
    "stepByStepSolutionAr": [
      "١. شرط الرنين وتكون الموجات الموقوفة في التجويف: $L = m \\frac{\\lambda}{2} = m \\frac{c}{2\\nu} \\implies \\nu_m = m \\frac{c}{2L}$.",
      "٢. التباعد الترددي بين نمطين متتاليين: $\\Delta\\nu = \\frac{c}{2L}$.",
      "٣. الحساب: $\\Delta\\nu = \\frac{3.0 \\times 10^8}{2 \\times 0.50} = 3.0 \\times 10^8\\text{ هرتز} = 300\\text{ ميجاهرتز}$."
    ],
    "teacherTipEn": "The longer the optical cavity length L, the closer the longitudinal resonant modes are packed in frequency space.",
    "teacherTipAr": "كلما زاد طول التجويف الرنيني L، قل التباعد الترددي بين الأنماط الرنينية الطولية وتزاحمت الخطوط."
  },
  {
    "id": "egbac_phys_ch3_se_06",
    "titleEn": "Threshold Optical Gain in Laser Cavity with End Mirrors",
    "titleAr": "معامل الكسب الضوئي الحرج في تجويف الليزر بمعلومية انعكاسية المرآتين",
    "difficulty": "hots",
    "questionEn": "A laser medium of length $L = 20\\text{ cm} = 0.20\\text{ m}$ is placed in an optical cavity with mirror reflectivities $R_1 = 1.0$ (totally reflecting) and $R_2 = 0.95$ (partially transmitting output coupler). Neglecting internal medium scattering losses ($\\alpha = 0$), calculate the threshold optical gain coefficient $\\gamma_{\\text{th}}$ per meter required for sustained steady-state lasing oscillation ($R_1 R_2 e^{2\\gamma_{\\text{th}} L} = 1$).",
    "questionAr": "وُضع وسط ليزري فعال طوله $L = 20\\text{ سم} = 0.20\\text{ م}$ داخل تجويف بصري انعكاسية مرآتيه $R_1 = 1.0$ (مرآة عاكسة تماماً) و $R_2 = 0.95$ (مرآة شبه منفذة تخرج الشعاع). بإهمال الفقد الداخلي بالتشتت، احسب معامل الكسب الحرج $\\gamma_{\\text{th}}$ لكل متر اللازم لاستمرار توليد الليزر في حالة الاستقرار ($R_1 R_2 e^{2\\gamma_{\\text{th}} L} = 1$).",
    "optionsEn": [
      "$0.256\\text{ m}^{-1}$",
      "$0.128\\text{ m}^{-1}$",
      "$0.064\\text{ m}^{-1}$",
      "$0.512\\text{ m}^{-1}$"
    ],
    "optionsAr": [
      "$0.256\\text{ م}^{-1}$",
      "$0.128\\text{ م}^{-1}$",
      "$0.064\\text{ م}^{-1}$",
      "$0.512\\text{ م}^{-1}$"
    ],
    "correctAnswer": "$0.128\\text{ m}^{-1}$",
    "correctIndex": 1,
    "hintEn": "Rearrange threshold equation: 2 * gamma_th * L = ln(1 / (R1 * R2)), so gamma_th = (1 / (2L)) * ln(1 / (R1 * R2)).",
    "hintAr": "أعد ترتيب معادلة الكسب الحرج: 2 * gamma_th * L = ln(1 / (R1 * R2))، ومنها gamma_th = (1 / (2L)) * ln(1 / (R1 * R2)).",
    "stepByStepSolutionEn": [
      "1. Threshold round-trip condition: $R_1 R_2 e^{2 \\gamma_{\\text{th}} L} = 1 \\implies e^{2 \\gamma_{\\text{th}} L} = \\frac{1}{R_1 R_2}$.",
      "2. Take natural logarithm: $2 \\gamma_{\\text{th}} L = \\ln\\left(\\frac{1}{R_1 R_2}\\right) \\implies \\gamma_{\\text{th}} = \\frac{1}{2L} \\ln\\left(\\frac{1}{R_1 R_2}\\right)$.",
      "3. Substitute numbers: $R_1 R_2 = 1.0 \\times 0.95 = 0.95$, so $\\frac{1}{0.95} \\approx 1.05263$.",
      "   $\\ln(1.05263) \\approx 0.05129$.",
      "4. Calculate: $\\gamma_{\\text{th}} = \\frac{0.05129}{2 \\times 0.20\\text{ m}} = \\frac{0.05129}{0.40} \\approx 0.1282\\text{ m}^{-1}$."
    ],
    "stepByStepSolutionAr": [
      "١. شرط الكسب الحرج لدورة كاملة: $R_1 R_2 e^{2 \\gamma_{\\text{th}} L} = 1$.",
      "٢. بأخذ اللوغاريتم الطبيعي: $\\gamma_{\\text{th}} = \\frac{1}{2L} \\ln\\left(\\frac{1}{R_1 R_2}\\right)$.",
      "٣. التعويض: $\\ln(1/0.95) = \\ln(1.05263) \\approx 0.05129$.",
      "٤. إذن: $\\gamma_{\\text{th}} = \\frac{0.05129}{0.40} \\approx 0.128\\text{ م}^{-1}$."
    ],
    "teacherTipEn": "The threshold gain exactly balances the transmission loss at the output mirror, keeping intra-cavity intensity constant.",
    "teacherTipAr": "يعوض معامل الكسب الحرج بدقة نسبة الطاقة الضوئية المنفذة عبر المرآة شبه المنفذة ليظل توليد الشعاع مستقراً."
  },
  {
    "id": "egbac_phys_ch3_se_07",
    "titleEn": "Temporal Coherence Length and Spectral Linewidth of a Laser",
    "titleAr": "طول الترابط الزمني والاتساع الطيفي لشعاع ليزر",
    "difficulty": "hots",
    "questionEn": "A highly stabilized single-mode Helium-Neon laser has a narrow spectral linewidth of $\\Delta\\nu = 10\\text{ kHz} = 1.0 \\times 10^4\\text{ Hz}$. Given $c = 3.0 \\times 10^8\\text{ m/s}$, calculate the temporal coherence time $\\tau_c = \\frac{1}{\\Delta\\nu}$ and the resulting coherence length $L_c = c \\tau_c$.",
    "questionAr": "يمتلك ليزر هيليوم - نيون أحادي النمط فائق الاستقرار اتساعاً طيفياً ضيقاً للغاية قدره $\\Delta\\nu = 10\\text{ كيلو هرتز} = 1.0 \\times 10^4\\text{ هرتز}$. بمعلومية سرعة الضوء $c = 3.0 \\times 10^8\\text{ م/ث}$، احسب زمن الترابط $\\tau_c = \\frac{1}{\\Delta\\nu}$ وطول الترابط الناتج $L_c = c \\tau_c$.",
    "optionsEn": [
      "$L_c = 30\\text{ m}$",
      "$L_c = 300\\text{ m}$",
      "$L_c = 30\\text{ km} \\; (3.0 \\times 10^4\\text{ m})$",
      "$L_c = 3.0\\text{ km}$"
    ],
    "optionsAr": [
      "$L_c = 30\\text{ م}$",
      "$L_c = 300\\text{ م}$",
      "$L_c = 30\\text{ كم} \\; (3.0 \\times 10^4\\text{ م})$",
      "$L_c = 3.0\\text{ كم}$"
    ],
    "correctAnswer": "$L_c = 30\\text{ km} \\; (3.0 \\times 10^4\\text{ m})$",
    "correctIndex": 2,
    "hintEn": "Coherence length L_c = c / Delta_nu.",
    "hintAr": "طول الترابط L_c = c / Delta_nu.",
    "stepByStepSolutionEn": [
      "1. Coherence time is the reciprocal of spectral linewidth: $\\tau_c = \\frac{1}{\\Delta\\nu} = \\frac{1}{1.0 \\times 10^4\\text{ s}^{-1}} = 1.0 \\times 10^{-4}\\text{ s} = 100\\,\\mu\\text{s}$.",
      "2. Coherence length is the physical distance over which phase correlation remains fixed: $L_c = c \\cdot \\tau_c = \\frac{c}{\\Delta\\nu}$.",
      "3. Calculate: $L_c = \\frac{3.0 \\times 10^8\\text{ m/s}}{1.0 \\times 10^4\\text{ s}^{-1}} = 3.0 \\times 10^4\\text{ m} = 30\\text{ km}$."
    ],
    "stepByStepSolutionAr": [
      "١. زمن الترابط: $\\tau_c = \\frac{1}{\\Delta\\nu} = \\frac{1}{10^4} = 10^{-4}\\text{ ثانية}$.",
      "٢. طول الترابط هو المسافة التي تظل فيها الموجة متفقة في الطور مع نفسها: $L_c = c \\tau_c = \\frac{c}{\\Delta\\nu}$.",
      "٣. الحساب: $L_c = \\frac{3.0 \\times 10^8}{10^4} = 30000\\text{ م} = 30\\text{ كم}$."
    ],
    "teacherTipEn": "By contrast, conventional white light from an incandescent bulb has a coherence length of only a few micrometers!",
    "teacherTipAr": "بالمقارنة، يبلغ طول الترابط للضوء الأبيض العادي من المصابيح المتوهجة بضعة ميكرومترات فقط!"
  },
  {
    "id": "egbac_phys_ch3_se_08",
    "titleEn": "Diffraction-Limited Beam Divergence and Spot Size on the Moon",
    "titleAr": "زاوية انفراج شعاع الليزر المحدودة بالحيود وحجم البقعة على سطح القمر",
    "difficulty": "hots",
    "questionEn": "A laser beam of wavelength $\\lambda = 532\\text{ nm}$ is directed at the Moon (distance $D_{\\text{Moon}} = 3.84 \\times 10^8\\text{ m}$) through a telescope aperture of diameter $d = 1.0\\text{ m}$. Using the Airy diffraction angular divergence $\\theta = 1.22 \\frac{\\lambda}{d}$, calculate the angular beam spread $\\theta$ and the resulting beam spot diameter on the lunar surface.",
    "questionAr": "أُطلق شعاع ليزر طوله الموجي $\\lambda = 532\\text{ نانومتر}$ نحو القمر (المسافة $D_{\\text{Moon}} = 3.84 \\times 10^8\\text{ م}$) عبر فتحة تلسكوب قطرها $d = 1.0\\text{ م}$. باستخدام زاوية انفراج حيود إيري $\\theta = 1.22 \\frac{\\lambda}{d}$، احسب زاوية انفراج الشعاع $\\theta$ وقطر بقعة الضوء الناتجة على سطح القمر.",
    "optionsEn": [
      "$\\theta = 1.30 \\times 10^{-6}\\text{ rad}, \\quad \\text{Spot Diameter} \\approx 996\\text{ m}$",
      "$\\theta = 3.25 \\times 10^{-7}\\text{ rad}, \\quad \\text{Spot Diameter} \\approx 249\\text{ m}$",
      "$\\theta = 5.32 \\times 10^{-7}\\text{ rad}, \\quad \\text{Spot Diameter} \\approx 204\\text{ m}$",
      "$\\theta = 6.49 \\times 10^{-7}\\text{ rad}, \\quad \\text{Spot Diameter} \\approx 498\\text{ m}$"
    ],
    "optionsAr": [
      "$\\theta = 1.30 \\times 10^{-6}\\text{ راديان}، \\quad \\text{قطر البقعة} \\approx 996\\text{ م}$",
      "$\\theta = 3.25 \\times 10^{-7}\\text{ راديان}، \\quad \\text{قطر البقعة} \\approx 249\\text{ م}$",
      "$\\theta = 5.32 \\times 10^{-7}\\text{ راديان}، \\quad \\text{قطر البقعة} \\approx 204\\text{ م}$",
      "$\\theta = 6.49 \\times 10^{-7}\\text{ راديان}، \\quad \\text{قطر البقعة} \\approx 498\\text{ م}$"
    ],
    "correctAnswer": "$\\theta = 6.49 \\times 10^{-7}\\text{ rad}, \\quad \\text{Spot Diameter} \\approx 498\\text{ m}$",
    "correctIndex": 3,
    "hintEn": "Calculate theta = 1.22 * lambda / d, then spot diameter = 2 * R * theta = D_Moon * theta.",
    "hintAr": "احسب theta = 1.22 * lambda / d، ثم قطر البقعة = D_Moon * theta.",
    "stepByStepSolutionEn": [
      "1. Angular divergence angle: $\\theta = 1.22 \\frac{\\lambda}{d} = 1.22 \\frac{532 \\times 10^{-9}\\text{ m}}{1.0\\text{ m}} \\approx 6.49 \\times 10^{-7}\\text{ rad}$.",
      "2. The beam spot diameter at distance $D$ is $w = D_{\\text{Moon}} \\cdot \\theta$.",
      "   $w = 3.84 \\times 10^8\\text{ m} \\times (6.49 \\times 10^{-7}\\text{ rad}) \\approx 498.8\\text{ m} \\approx 498\\text{ m}$."
    ],
    "stepByStepSolutionAr": [
      "١. زاوية انفراج الشعاع: $\\theta = 1.22 \\frac{\\lambda}{d} = 1.22 \\times \\frac{532 \\times 10^{-9}}{1.0} \\approx 6.49 \\times 10^{-7}\\text{ راديان}$.",
      "٢. قطر بقعة الضوء على القمر: $w = D_{\\text{Moon}} \\cdot \\theta = 3.84 \\times 10^8 \\times 6.49 \\times 10^{-7} \\approx 498\\text{ متراً}$."
    ],
    "teacherTipEn": "Despite traveling nearly 400,000 km across space, the beam expands to less than half a kilometer, illustrating extreme collimation.",
    "teacherTipAr": "رغم قطع مسافة تقارب 400 ألف كيلومتر في الفضاء، لم يتسع الشعاع إلا لحوالي نصف كيلومتر فقط، مما يثبت ميزة التوازي الشديد لليزر."
  },
  {
    "id": "egbac_phys_ch3_se_09",
    "titleEn": "Principles of Optical Holography vs Conventional Photography",
    "titleAr": "أسس التصوير المجسم (الهولوجرافيا) ومقارنتها بالتصوير الفوتوغرافي التقليدي",
    "difficulty": "medium",
    "questionEn": "What fundamental optical difference enables holography to reconstruct a complete 3-dimensional image of an object, unlike ordinary 2-dimensional photography?",
    "questionAr": "ما الفارق الضوئي الجوهري الذي يمكّن الهولوجرام من إعادة بناء صورة ثلاثية الأبعاد كاملة للجسم، على عكس التصوير الفوتوغرافي التقليدي ثنائي الأبعاد؟",
    "optionsEn": [
      "Holography records both amplitude (intensity) and phase of light waves via interference; photography records only intensity.",
      "Holography uses infrared radiation while photography uses ultraviolet radiation.",
      "Holography uses convex lenses with very high magnification; photography uses concave lenses.",
      "Holography records only magnetic field lines; photography records only electric field lines."
    ],
    "optionsAr": [
      "تسجل الهولوجرافيا كلاً من السعة (الشدة) والطور للموجات عبر التداخل؛ بينما يسجل التصوير التقليدي الشدة الضوئية فقط.",
      "تستخدم الهولوجرافيا أشعة تحت حمراء بينما يستخدم التصوير التقليدي أشعة فوق بنفسجية.",
      "تستخدم الهولوجرافيا عدسات محدبة ذات تكبير فائق؛ بينما يستخدم التصوير التقليدي عدسات مقعرة.",
      "تسجل الهولوجرافيا خطوط المجال المغناطيسي فقط؛ بينما يسجل التصوير الفوتوغرافي المجال الكهربي فقط."
    ],
    "correctAnswer": "Holography records both amplitude (intensity) and phase of light waves via interference; photography records only intensity.",
    "correctIndex": 0,
    "hintEn": "Photographic plates respond only to intensity (proportional to amplitude squared). Holography uses a reference beam to record phase through interference fringes.",
    "hintAr": "تتأثر اللوحة الفوتوغرافية بشدة الضوء فقط (مربع السعة). وتعتمد الهولوجرافيا على حزمة مرجعية لتسجيل الطور بتداخل الموجات وتكون أهداب التداخل.",
    "stepByStepSolutionEn": [
      "1. In standard photography, photographic film records only irradiance (intensity $I \\propto A^2$), completely discarding the phase information $\\phi(x, y)$. This flattens the image into 2 dimensions.",
      "2. In Dennis Gabor's holography, coherent laser light is split into an **object beam** and a **reference beam**.",
      "3. The interference pattern of these two beams encodes both relative phase differences (depth information) and wave amplitudes across the holographic plate as microscopic interference fringes."
    ],
    "stepByStepSolutionAr": [
      "١. في التصوير العادي: يسجل الفيلم شدة الضوء فقط ($I \\propto A^2$) ويفقد معلومات الطور والعمق ($\\phi$) فتظهر الصورة مسطحة في بعدين.",
      "٢. في الهولوجرافيا (ابتكار دينيس جابور): يُقسم ضوء الليزر المترابط إلى **شعاع جسم** منعكس من الجسم و**شعاع مرجعي** نقي.",
      "٣. يُحدث تداخل الحزمتين نمط أهداب تداخل مجهري يسجل كلاً من سعة الموجات وطورها، مما يحفظ الأبعاد الثلاثية وعمق التضاريس كاملاً."
    ],
    "teacherTipEn": "Illuminating the developed hologram with the reference beam diffracts the light to reconstruct the original 3D wavefront perfectly!",
    "teacherTipAr": "عند إضاءة لوح الهولوجرام بالشعاع المرجعي، تحيد الموجات لتعيد بناء صدر الموجة الأصلي ثلاثي الأبعاد بالكامل أمام عين المشاهد!"
  },
  {
    "id": "egbac_phys_ch3_se_10",
    "titleEn": "Focused Power Density in Industrial Laser Cutting & Surgery",
    "titleAr": "كثافة القدرة الضوئية المركزة في القطع الصناعي والجراحة بالليزر",
    "difficulty": "medium",
    "questionEn": "A continuous infrared $\\text{CO}_2$ laser with output power $P = 200\\text{ W}$ is focused by a zinc selenide lens to a circular diffraction spot of diameter $d = 0.10\\text{ mm} = 1.0 \\times 10^{-4}\\text{ m}$. Calculate the optical power density (intensity $I$ in $\\text{W/cm}^2$) at the focal spot.",
    "questionAr": "يُركز شعاع ليزر ثاني أكسيد الكربون المستمر بقدرة $P = 200\\text{ واط}$ بواسطة عدسة خاصة إلى بقعة دائرية بؤرية قطرها $d = 0.10\\text{ مم} = 1.0 \\times 10^{-4}\\text{ م}$. احسب كثافة القدرة الضوئية (الشدة $I$ بوحدة $\\text{W/cm}^2$) عند هذه البقعة البؤرية.",
    "optionsEn": [
      "$1.28 \\times 10^6\\text{ W/cm}^2$",
      "$2.55 \\times 10^6\\text{ W/cm}^2$",
      "$5.10 \\times 10^5\\text{ W/cm}^2$",
      "$2.55 \\times 10^4\\text{ W/cm}^2$"
    ],
    "optionsAr": [
      "$1.28 \\times 10^6\\text{ واط/سم}^2$",
      "$2.55 \\times 10^6\\text{ واط/سم}^2$",
      "$5.10 \\times 10^5\\text{ واط/سم}^2$",
      "$2.55 \\times 10^4\\text{ واط/سم}^2$"
    ],
    "correctAnswer": "$2.55 \\times 10^6\\text{ W/cm}^2$",
    "correctIndex": 1,
    "hintEn": "Calculate focal area A = pi * (d/2)^2 in cm^2, then intensity I = P / A.",
    "hintAr": "احسب مساحة البقعة A = pi * (d/2)^2 بوحدة سم^2، ثم الشدة I = P / A.",
    "stepByStepSolutionEn": [
      "1. Radius of focal spot: $r = \\frac{d}{2} = 0.05\\text{ mm} = 0.005\\text{ cm} = 5.0 \\times 10^{-3}\\text{ cm}$.",
      "2. Area of focal spot: $A = \\pi r^2 = \\pi (5.0 \\times 10^{-3}\\text{ cm})^2 \\approx 7.854 \\times 10^{-5}\\text{ cm}^2$.",
      "3. Power density: $I = \\frac{P}{A} = \\frac{200\\text{ W}}{7.854 \\times 10^{-5}\\text{ cm}^2} \\approx 2.546 \\times 10^6\\text{ W/cm}^2$."
    ],
    "stepByStepSolutionAr": [
      "١. نصف قطر البؤرة: $r = 0.05\\text{ مم} = 5.0 \\times 10^{-3}\\text{ سم}$.",
      "٢. مساحة البقعة: $A = \\pi r^2 = 3.1416 \\times (5.0 \\times 10^{-3})^2 \\approx 7.854 \\times 10^{-5}\\text{ سم}^2$.",
      "٣. كثافة القدرة المركزة: $I = \\frac{200}{7.854 \\times 10^{-5}} \\approx 2.55 \\times 10^6\\text{ واط/سم}^2$."
    ],
    "teacherTipEn": "This enormous concentrated power density instantly vaporizes refractory metals and cauterizes blood vessels during surgery.",
    "teacherTipAr": "هذه الكثافة الهائلة للقدرة تبخر أصلب المعادن فورياً في الصناعة، وتكوي الأوعية الدموية وتوقف النزيف جراحياً."
  }
];

export const egBacPhysCh3Exercises: SolvedProblem[] = [
  {
    "id": "egbac_phys_ch3_ex_01",
    "titleEn": "Lifetime Comparison: Normal Excited State vs Metastable Level",
    "titleAr": "مقارنة فترة العمر بين مستوى الإثارة العادي ومستوى شبه الاستقرار",
    "difficulty": "easy",
    "questionEn": "How does the characteristic lifetime of an electron in a metastable state compare to that in an ordinary excited atomic level?",
    "questionAr": "كيف تُقارَن فترة العمر المعتادة لذرة في مستوى شبه استقرار بفترة عمرها في مستوى إثارة عادي؟",
    "optionsEn": [
      "Metastable state: $\\sim 10^{-8}\\text{ s}$; Ordinary excited level: $\\sim 10^{-3}\\text{ s}$.",
      "Metastable state: $\\sim 10^{-12}\\text{ s}$; Ordinary excited level: $\\sim 10^{-6}\\text{ s}$.",
      "Metastable state: $\\sim 10^{-3}\\text{ s}$; Ordinary excited level: $\\sim 10^{-8}\\text{ s}$ (about $10^5$ times longer).",
      "Both have identical lifetimes of $\\sim 10^{-4}\\text{ s}$."
    ],
    "optionsAr": [
      "مستوى شبه الاستقرار: $\\sim 10^{-8}\\text{ ث}$؛ مستوى الإثارة العادي: $\\sim 10^{-3}\\text{ ث}$.",
      "مستوى شبه الاستقرار: $\\sim 10^{-12}\\text{ ث}$؛ مستوى الإثارة العادي: $\\sim 10^{-6}\\text{ ث}$.",
      "مستوى شبه الاستقرار: $\\sim 10^{-3}\\text{ ث}$؛ مستوى الإثارة العادي: $\\sim 10^{-8}\\text{ ث}$ (أطول بنحو مئة ألف مرة).",
      "كلاهما لهما نفس فترة العمر تماماً وتساوي $\\sim 10^{-4}\\text{ ث}$."
    ],
    "correctAnswer": "Metastable state: $\\sim 10^{-3}\\text{ s}$; Ordinary excited level: $\\sim 10^{-8}\\text{ s}$ (about $10^5$ times longer).",
    "correctIndex": 2,
    "hintEn": "Metastable states have forbidden optical dipole transitions.",
    "hintAr": "مستويات شبه الاستقرار تكون الانتقالات منها محظورة بقواعد الاختيار البصرية.",
    "stepByStepSolutionEn": [
      "1. Ordinary excited atomic states have lifetimes on the order of $10^{-8}\\text{ s}$.",
      "2. Metastable states hold electrons for around $10^{-3}\\text{ s}$, which is roughly $100,000$ times longer."
    ],
    "stepByStepSolutionAr": [
      "١. تبلغ فترة العمر لمستويات الإثارة العادية حوالي $10^{-8}\\text{ ثانية}$.",
      "٢. تبلغ فترة العمر لمستويات شبه الاستقرار حوالي $10^{-3}\\text{ ثانية}$ وهي أطول بنحو مئة ألف مرة."
    ],
    "teacherTipEn": "A metastable state traps the excited electron for a remarkably extended duration.",
    "teacherTipAr": "يحتجز مستوى شبه الاستقرار الإلكترون المثار لفترة أطول بكثير مما يتيح تراكم الذرات."
  },
  {
    "id": "egbac_phys_ch3_ex_02",
    "titleEn": "Auxiliary Function of Helium Gas in the He-Ne Laser Mixture",
    "titleAr": "الوظيفة المساعدة لغاز الهيليوم في خليط ليزر الهيليوم - نيون",
    "difficulty": "easy",
    "questionEn": "Why is Helium gas mixed with Neon gas in a Helium-Neon laser instead of using pure Neon gas alone?",
    "questionAr": "لماذا يُخلط غاز الهيليوم مع غاز النيون في ليزر الهيليوم - نيون بدلاً من استخدام غاز النيون النقي منفرداً؟",
    "optionsEn": [
      "Helium directly generates the laser photons; Neon is merely a protective buffer.",
      "Helium prevents the glass envelope from melting by cooling the laser cavity.",
      "Helium chemically combines with neon to form an unstable diatomic molecule.",
      "Helium has high excitation efficiency by electron collision, transferring energy resonantly to Neon to achieve inversion."
    ],
    "optionsAr": [
      "الهيليوم هو الذي يشع فوتونات الليزر مباشرة؛ والنيون مجرد غاز واقٍ.",
      "يمنع الهيليوم انصهار الأنبوب الزجاجي عن طريق تبريد التجويف.",
      "يتحد الهيليوم كيميائياً مع النيون لتكوين جزيء ثنائي الذرة غير مستقر.",
      "يمتلك الهيليوم كفاءة إثارة عالية بتصادم الإلكترونات، وينقل طاقته بالرنين لذرات النيون لتحقيق الإسكان المعكوس."
    ],
    "correctAnswer": "Helium has high excitation efficiency by electron collision, transferring energy resonantly to Neon to achieve inversion.",
    "correctIndex": 3,
    "hintEn": "Direct electron impact excitation of neon is very inefficient; helium provides the resonant bridge.",
    "hintAr": "إثارة النيون مباشرة بتصادم الإلكترونات ضعيفة الكفاءة؛ ويوفر الهيليوم جسر نقل الطاقة الرنيني.",
    "stepByStepSolutionEn": [
      "1. Helium atoms are excited efficiently by electric discharge to their $20.66\\text{ eV}$ level.",
      "2. Inelastic collisions transfer this energy directly to Neon's $20.61\\text{ eV}$ level."
    ],
    "stepByStepSolutionAr": [
      "١. تُثار ذرات الهيليوم بكفاءة عالية بالتفريغ الكهربي إلى مستواها شبه المستقر ($20.66\\text{ eV}$).",
      "٢. تنقل ذرات الهيليوم طاقتها بالرنين لذرات النيون ذات المستوى المتقارب ($20.61\\text{ eV}$)."
    ],
    "teacherTipEn": "Helium acts as an efficient pumping intermediary for the active Neon medium.",
    "teacherTipAr": "يعمل الهيليوم كوسيط ضخ عالي الكفاءة لذرات النيون الفعالة."
  },
  {
    "id": "egbac_phys_ch3_ex_03",
    "titleEn": "Resonant Mode Number in an Optical Resonator",
    "titleAr": "رتبة النمط الرنيني لموجة موقوفة داخل تجويف بصري",
    "difficulty": "medium",
    "questionEn": "A red laser of wavelength $\\lambda = 632.8\\text{ nm}$ oscillates in a cavity of length $L = 31.64\\text{ cm} = 0.3164\\text{ m}$. How many half-wavelengths ($m$) fit inside the cavity according to the resonance condition $L = m \\frac{\\lambda}{2}$?",
    "questionAr": "يتذبذب شعاع ليزر أحمر طوله الموجي $\\lambda = 632.8\\text{ نانومتر}$ في تجويف بصري طوله $L = 31.64\\text{ سم} = 0.3164\\text{ م}$. كم نصف طول موجي ($m$) يحتوي هذا التجويف وفق شرط الرنين للموجات الموقوفة $L = m \\frac{\\lambda}{2}$؟",
    "optionsEn": [
      "$m = 1,000,000 \\; (1.0 \\times 10^6)$",
      "$m = 500,000$",
      "$m = 2,000,000$",
      "$m = 100,000$"
    ],
    "optionsAr": [
      "$m = 1,000,000 \\; (1.0 \\times 10^6)$",
      "$m = 500,000$",
      "$m = 2,000,000$",
      "$m = 100,000$"
    ],
    "correctAnswer": "$m = 1,000,000 \\; (1.0 \\times 10^6)$",
    "correctIndex": 0,
    "hintEn": "Calculate m = 2 * L / lambda.",
    "hintAr": "احسب m = 2 * L / lambda.",
    "stepByStepSolutionEn": [
      "1. Resonance condition: $L = m \\frac{\\lambda}{2} \\implies m = \\frac{2L}{\\lambda}$.",
      "2. Convert length and wavelength: $L = 0.3164\\text{ m}$, $\\lambda = 632.8 \\times 10^{-9}\\text{ m}$.",
      "3. Calculate: $m = \\frac{2 \\times 0.3164\\text{ m}}{632.8 \\times 10^{-9}\\text{ m}} = 1,000,000$."
    ],
    "stepByStepSolutionAr": [
      "١. شرط رنين الموجة الموقوفة: $m = \\frac{2L}{\\lambda}$.",
      "٢. بالتعويض: $m = \\frac{2 \\times 0.3164}{632.8 \\times 10^{-9}}$.",
      "٣. الناتج: $m = 1,000,000$ (مليون نصف موجة موقوفة بالضبط)."
    ],
    "teacherTipEn": "Because m is an extremely large integer, laser resonators support numerous closely spaced longitudinal modes.",
    "teacherTipAr": "نظراً لكبر رتبة النمط m، يحتوي التجويف على أنماط طولية متقاربة عديدة ما لم يتم وضع مرشحات انتقائية."
  },
  {
    "id": "egbac_phys_ch3_ex_04",
    "titleEn": "Monochromaticity Purity Ratio of a Narrowband Laser",
    "titleAr": "نسبة النقاء الطيفي أحادي اللون لشعاع ليزر ضيق النطاق",
    "difficulty": "easy",
    "questionEn": "A laboratory laser operating at $\\lambda_0 = 600\\text{ nm}$ has a spectral linewidth of $\\Delta\\lambda = 0.006\\text{ nm}$. What is its monochromaticity purity ratio $\\frac{\\Delta\\lambda}{\\lambda_0}$?",
    "questionAr": "يعمل ليزر مختبري عند طول موجي $\\lambda_0 = 600\\text{ نانومتر}$ باتساع خط طيفي قدره $\\Delta\\lambda = 0.006\\text{ نانومتر}$. ما نسبة النقاء الطيفي أحادي اللون $\\frac{\\Delta\\lambda}{\\lambda_0}$؟",
    "optionsEn": [
      "$1.0 \\times 10^{-3}$",
      "$1.0 \\times 10^{-5}$",
      "$1.0 \\times 10^{-7}$",
      "$6.0 \\times 10^{-5}$"
    ],
    "optionsAr": [
      "$1.0 \\times 10^{-3}$",
      "$1.0 \\times 10^{-5}$",
      "$1.0 \\times 10^{-7}$",
      "$6.0 \\times 10^{-5}$"
    ],
    "correctAnswer": "$1.0 \\times 10^{-5}$",
    "correctIndex": 1,
    "hintEn": "Calculate Delta lambda / lambda_0.",
    "hintAr": "احسب النسبة Delta lambda / lambda_0.",
    "stepByStepSolutionEn": [
      "1. Fractional spectral linewidth: $\\frac{\\Delta\\lambda}{\\lambda_0} = \\frac{0.006\\text{ nm}}{600\\text{ nm}} = 1.0 \\times 10^{-5}$.",
      "2. This extremely small spread demonstrates the extraordinary monochromaticity of laser light."
    ],
    "stepByStepSolutionAr": [
      "١. نسبة الاتساع الطيفي: $\\frac{\\Delta\\lambda}{\\lambda_0} = \\frac{0.006}{600} = 1.0 \\times 10^{-5}$.",
      "٢. هذا الاتساع الضئيل جداً يوضح النقاء الطيفي الفائق لضوء الليزر مقارنة بالمصادر العادية."
    ],
    "teacherTipEn": "Monochromaticity is essential for interferometry, spectroscopy, and dense optical fiber multiplexing.",
    "teacherTipAr": "النقاء الطيفي ضروري لتطبيقات التداخل الضوئي والمطيافية ونقل البيانات في الألياف البصرية."
  },
  {
    "id": "egbac_phys_ch3_ex_05",
    "titleEn": "Threshold Population Inversion Density for Laser Oscillation",
    "titleAr": "كثافة الإسكان المعكوس الحرجة لبدء التوليد الليزري",
    "difficulty": "hots",
    "questionEn": "The small-signal optical gain coefficient of a laser medium is proportional to the population inversion density: $\\gamma = \\sigma (N_2 - N_1)$, where $\\sigma = 2.5 \\times 10^{-20}\\text{ cm}^2 = 2.5 \\times 10^{-24}\\text{ m}^2$ is the stimulated emission cross-section. If the required threshold gain for lasing is $\\gamma_{\\text{th}} = 0.20\\text{ m}^{-1}$, what is the minimum population inversion density $(N_2 - N_1)_{\\text{th}}$ per cubic meter?",
    "questionAr": "يتناسب معامل الكسب الضوئي للوسط مع كثافة الإسكان المعكوس: $\\gamma = \\sigma (N_2 - N_1)$، حيث $\\sigma = 2.5 \\times 10^{-24}\\text{ م}^2$ مقطع مساحة الانبعاث المستحث. إذا كان الكسب الحرج المطلوب لتشغيل الليزر هو $\\gamma_{\\text{th}} = 0.20\\text{ م}^{-1}$، فما الحد الأدنى لكثافة الإسكان المعكوس $(N_2 - N_1)_{\\text{th}}$ في المتر المكعب الواحد؟",
    "optionsEn": [
      "$4.0 \\times 10^{22}\\text{ atoms/m}^3$",
      "$1.6 \\times 10^{23}\\text{ atoms/m}^3$",
      "$8.0 \\times 10^{22}\\text{ atoms/m}^3$",
      "$5.0 \\times 10^{21}\\text{ atoms/m}^3$"
    ],
    "optionsAr": [
      "$4.0 \\times 10^{22}\\text{ ذرة/م}^3$",
      "$1.6 \\times 10^{23}\\text{ ذرة/م}^3$",
      "$8.0 \\times 10^{22}\\text{ ذرة/م}^3$",
      "$5.0 \\times 10^{21}\\text{ ذرة/م}^3$"
    ],
    "correctAnswer": "$8.0 \\times 10^{22}\\text{ atoms/m}^3$",
    "correctIndex": 2,
    "hintEn": "Formula: (N_2 - N_1) = gamma_th / sigma.",
    "hintAr": "القانون: (N_2 - N_1) = gamma_th / sigma.",
    "stepByStepSolutionEn": [
      "1. Relate gain to inversion density: $\\gamma_{\\text{th}} = \\sigma \\Delta N_{\\text{th}} \\implies \\Delta N_{\\text{th}} = \\frac{\\gamma_{\\text{th}}}{\\sigma}$.",
      "2. Substitute values: $\\Delta N_{\\text{th}} = \\frac{0.20\\text{ m}^{-1}}{2.5 \\times 10^{-24}\\text{ m}^2} = 8.0 \\times 10^{22}\\text{ atoms/m}^3$."
    ],
    "stepByStepSolutionAr": [
      "١. علاقة الكسب بكثافة الإسكان المعكوس: $\\Delta N_{\\text{th}} = \\frac{\\gamma_{\\text{th}}}{\\sigma}$.",
      "٢. الحساب: $\\Delta N_{\\text{th}} = \\frac{0.20}{2.5 \\times 10^{-24}} = 8.0 \\times 10^{22}\\text{ ذرة/م}^3$."
    ],
    "teacherTipEn": "If the pumping rate cannot maintain this inversion threshold, lasing oscillation terminates.",
    "teacherTipAr": "إذا عجز معدل الضخ عن الحفاظ على هذا الحد الأدنى لكثافة الإسكان المعكوس، يتوقف انبعاث الليزر."
  },
  {
    "id": "egbac_phys_ch3_ex_06",
    "titleEn": "Coherence Length of a Semiconductor Diode Laser",
    "titleAr": "طول الترابط لشبه موصل ليزري ثنائي",
    "difficulty": "medium",
    "questionEn": "A compact semiconductor laser diode operates at wavelength $\\lambda = 800\\text{ nm}$ with a spectral linewidth of $\\Delta\\lambda = 0.08\\text{ nm}$. Determine its coherence length $L_c \\approx \\frac{\\lambda^2}{\\Delta\\lambda}$.",
    "questionAr": "يعمل ليزر دايود شبه موصل عند طول موجي $\\lambda = 800\\text{ نانومتر}$ مع اتساع طيفي قدره $\\Delta\\lambda = 0.08\\text{ نانومتر}$. احسب طول الترابط المصاحب له $L_c \\approx \\frac{\\lambda^2}{\\Delta\\lambda}$.",
    "optionsEn": [
      "$0.80\\text{ mm}$",
      "$80\\text{ mm}$",
      "$8.0\\text{ cm}$",
      "$8.0\\text{ mm} \\; (8.0 \\times 10^{-3}\\text{ m})$"
    ],
    "optionsAr": [
      "$0.80\\text{ مم}$",
      "$80\\text{ مم}$",
      "$8.0\\text{ سم}$",
      "$8.0\\text{ مم} \\; (8.0 \\times 10^{-3}\\text{ م})$"
    ],
    "correctAnswer": "$8.0\\text{ mm} \\; (8.0 \\times 10^{-3}\\text{ m})$",
    "correctIndex": 3,
    "hintEn": "Formula: L_c = lambda^2 / Delta_lambda. Express both in same units.",
    "hintAr": "القانون: L_c = lambda^2 / Delta_lambda مع التعبير عنهما بنفس الوحدات.",
    "stepByStepSolutionEn": [
      "1. Coherence length in terms of wavelength spread: $L_c \\approx \\frac{\\lambda^2}{\\Delta\\lambda}$.",
      "2. Substitute values: $L_c = \\frac{(800\\text{ nm})^2}{0.08\\text{ nm}} = \\frac{640,000\\text{ nm}^2}{0.08\\text{ nm}} = 8,000,000\\text{ nm} = 8.0\\text{ mm}$."
    ],
    "stepByStepSolutionAr": [
      "١. طول الترابط بدلالة الطول الموجي: $L_c \\approx \\frac{\\lambda^2}{\\Delta\\lambda}$.",
      "٢. الحساب: $L_c = \\frac{800^2}{0.08} = 8,000,000\\text{ نانومتر} = 8.0\\text{ مم}$."
    ],
    "teacherTipEn": "While shorter than gas lasers, 8 mm is still thousands of times greater than the coherence length of non-laser diodes (LEDs).",
    "teacherTipAr": "رغم أنه أقصر من ليزرات الغاز، إلا أن 8 مم تفوق طول ترابط مصابيح الدايود العادية (LED) بآلاف المرات."
  },
  {
    "id": "egbac_phys_ch3_ex_07",
    "titleEn": "Function of the Output Coupler in a Laser Optical Resonator",
    "titleAr": "وظيفة المرآة شبه المنفذة في المرنان البصري لليزر",
    "difficulty": "easy",
    "questionEn": "What is the primary function of the partially transmitting mirror (output coupler) placed at one end of a laser cavity?",
    "questionAr": "ما الوظيفة الأساسية للمرآة شبه المنفذة المثبتة عند أحد طرفي تجويف الليزر؟",
    "optionsEn": [
      "It reflects most photons back to sustain stimulated emission while allowing a small fraction to exit as the output beam.",
      "It absorbs all reflected radiation to protect the power supply from electrical feedback.",
      "It filters out infrared light to convert the laser into visible radiation.",
      "It polarizes the light along two perpendicular axes simultaneously."
    ],
    "optionsAr": [
      "تعكس معظم الفوتونات لتعود للوسط وتواصل الانبعاث المستحث، وتسمح لجزء ضئيل بالنفاذ كشعاع ليزر خارج.",
      "تمتص كل الإشعاع المنعكس لحماية مصدر الطاقة من التغذية المرتدة.",
      "ترشح الأشعة تحت الحمراء لتحويل الليزر إلى إشعاع مرئي.",
      "تستقطب الضوء في اتجاهين متعامدين في نفس اللحظة."
    ],
    "correctAnswer": "It reflects most photons back to sustain stimulated emission while allowing a small fraction to exit as the output beam.",
    "correctIndex": 0,
    "hintEn": "The output mirror reflects ~95-99% to maintain the intra-cavity cascade, transmitting ~1-5% as the useful laser beam.",
    "hintAr": "تعكس المرآة شبه المنفذة ما بين 95% و 99% من الفوتونات للحفاظ على التضخيم، وتنفذ النسبة الباقية كشعاع ليزر مفيد.",
    "stepByStepSolutionEn": [
      "1. The output coupler reflects approximately 95% to 99% of laser photons back into the gain medium to maintain stimulated emission.",
      "2. The remaining 1% to 5% transmits through the mirror to form the external useful laser beam."
    ],
    "stepByStepSolutionAr": [
      "١. تعكس المرآة شبه المنفذة ما بين 95% إلى 99% من الفوتونات لتعود إلى الوسط الفعال وتواصل التضخيم بالانبعاث المستحث.",
      "٢. تسمح للنسبة الباقية (1% إلى 5%) بالنفاذ لتشكل حزمة الليزر الخارجية المفيدة."
    ],
    "teacherTipEn": "The transmission percentage is chosen to match threshold gain and maximize output power.",
    "teacherTipAr": "تُحدد نسبة نفاذية المرآة بدقة لموازنة الكسب الحرج واستخلاص أقصى قدرة ليزرية ممكنة."
  },
  {
    "id": "egbac_phys_ch3_ex_08",
    "titleEn": "Energy Difference Between Helium and Neon Metastable Levels",
    "titleAr": "فرق الطاقة بين المستويين شبه المستقرين للهيليوم والنيون",
    "difficulty": "easy",
    "questionEn": "The helium metastable level lies at $E_{\\text{He}} = 20.66\\text{ eV}$ and the corresponding neon level lies at $E_{\\text{Ne}} = 20.61\\text{ eV}$. What is the energy difference $\\Delta E$ that is transferred to/from kinetic energy during their collision?",
    "questionAr": "يقع مستوى شبه الاستقرار للهيليوم عند $E_{\\text{He}} = 20.66\\text{ إلكترون فولت}$ ومستوى النيون المناظر عند $E_{\\text{Ne}} = 20.61\\text{ إلكترون فولت}$. ما فرق الطاقة $\\Delta E$ الذي يتحول إلى/من طاقة الحركة أثناء تصادمهما؟",
    "optionsEn": [
      "$\\Delta E = 0.50\\text{ eV}$",
      "$\\Delta E = 0.05\\text{ eV}$",
      "$\\Delta E = 0.005\\text{ eV}$",
      "$\\Delta E = 1.05\\text{ eV}$"
    ],
    "optionsAr": [
      "$\\Delta E = 0.50\\text{ إلكترون فولت}$",
      "$\\Delta E = 0.05\\text{ إلكترون فولت}$",
      "$\\Delta E = 0.005\\text{ إلكترون فولت}$",
      "$\\Delta E = 1.05\\text{ إلكترون فولت}$"
    ],
    "correctAnswer": "$\\Delta E = 0.05\\text{ eV}$",
    "correctIndex": 1,
    "hintEn": "Subtract the two energies: 20.66 eV - 20.61 eV = 0.05 eV.",
    "hintAr": "اطرح الطاقتين: 20.66 - 20.61 = 0.05 إلكترون فولت.",
    "stepByStepSolutionEn": [
      "1. Energy gap between metastable states: $\\Delta E = 20.66\\text{ eV} - 20.61\\text{ eV} = 0.05\\text{ eV}$.",
      "2. Because this difference is comparable to thermal kinetic energy at room temperature ($k_B T \\approx 0.026\\text{ eV}$), collisional transfer is extraordinarily efficient."
    ],
    "stepByStepSolutionAr": [
      "١. فرق طاقتي المستويين: $\\Delta E = 20.66 - 20.61 = 0.05\\text{ إلكترون فولت}$.",
      "٢. لتقارب هذا الفارق الضئيل مع طاقة الحركة الحرارية العادية، يحدث الانتقال الرنيني بكفاءة استثنائية."
    ],
    "teacherTipEn": "This tiny energy difference is readily absorbed by the slight recoil motion of the colliding gas atoms.",
    "teacherTipAr": "يمتص هذا الفارق البسيط بسهولة كطاقة حركة ارتداد طفيفة للذرتين المتصادمتين."
  },
  {
    "id": "egbac_phys_ch3_ex_09",
    "titleEn": "Laser Application: Photocoagulation in Retinal Detachment",
    "titleAr": "تطبيق الليزر: التحام شبكية العين المنفصلة بالتخثير الضوئي",
    "difficulty": "easy",
    "questionEn": "Which unique characteristic of laser light makes it ideal for treating detached retinas in ophthalmic surgery without damaging surrounding tissue?",
    "questionAr": "أي من الخصائص الفريدة لشعاع الليزر تجعله مثالياً لعلاج انفصال شبكية العين جراحياً دون إتلاف الأنسجة المحيطة؟",
    "optionsEn": [
      "Its low speed in vitreous humor preventing shockwaves.",
      "Its broad multicolored continuous spectrum that illuminates the eye interior.",
      "Extreme collimation and sharp focusability, allowing thermal energy to be concentrated precisely on tiny retinal tears.",
      "Its ability to ionize eye humors to create magnetic fields."
    ],
    "optionsAr": [
      "سرعته البطيئة داخل السائل الزجاجي مما يمنع الموجات الصادمة.",
      "طيفه المتعدد الألوان الواسع الذي ينير باطن العين.",
      "التوازي الشديد والقدرة على التركيز فائق الدقة، مما يتيح توجيه طاقة حرارية مركزة تماماً على مواضع تمزق الشبكية.",
      "قدرته على تأيين سوائل العين لإنشاء مجالات مغناطيسية."
    ],
    "correctAnswer": "Extreme collimation and sharp focusability, allowing thermal energy to be concentrated precisely on tiny retinal tears.",
    "correctIndex": 2,
    "hintEn": "Argon and diode lasers produce sharp focal spots that weld tears through photocoagulation.",
    "hintAr": "تُركز أشعة الليزر في بقع مجهرية بالغة الدقة لتلحم أطراف الشبكية الممزقة بالتخثير الحراري الموضعي.",
    "stepByStepSolutionEn": [
      "1. The laser beam can be focused by the eye's natural lens onto a tiny spot on the retina.",
      "2. The localized heat coagulates protein and creates a weld without incisions."
    ],
    "stepByStepSolutionAr": [
      "١. تُركز عدسة العين الطبيعية شعاع الليزر المتوازي على بقعة بؤرية بالغة الصغر في الشبكية.",
      "٢. تُحدث الحرارة الموضعية تخثراً للبروتين مما يلحم نسيج الشبكية دون أي شق جراحي."
    ],
    "teacherTipEn": "Argon lasers emitting green light (514 nm) are preferentially absorbed by retinal hemoglobin and melanin.",
    "teacherTipAr": "يُمتص ليزر الأرجون الأخضر (514 نانومتر) بكفاءة عالية بواسطة صبغة الميلانين والهيموجلوبين في قاع العين."
  },
  {
    "id": "egbac_phys_ch3_ex_10",
    "titleEn": "Role of the Reference Beam in Holographic Recording",
    "titleAr": "دور الحزمة المرجعية في تسجيل الصورة المجسمة (الهولوجرام)",
    "difficulty": "medium",
    "questionEn": "In optical holography, what role does the reference beam play when it interferes with the object beam at the photographic plate?",
    "questionAr": "في التصوير المجسم (الهولوجرافيا)، ما الدور الذي تؤديه الحزمة المرجعية عند تداخلها مع حزمة الجسم على اللوح الفوتوغرافي؟",
    "optionsEn": [
      "It illuminates the dark room to allow the photographer to inspect the equipment.",
      "It chemically develops the silver halide grains during exposure.",
      "It reflects light directly away from the plate to reduce thermal background.",
      "It provides a known phase standard that converts phase variations into recorded intensity fringe modulations."
    ],
    "optionsAr": [
      "تضيء الغرفة المعتمة لتمكين الفاحص من ضبط الأجهزة.",
      "تُظهر الحبيبات الفضية كيميائياً أثناء التعريض الضوئي مباشرة.",
      "تعكس الضوء بعيداً عن اللوح لتقليل الإشعاع الحراري.",
      "توفر معيار طور معروف وثابت يحول تغيرات طور موجات الجسم إلى تغيرات شدة تسجلها أهداب التداخل."
    ],
    "correctAnswer": "It provides a known phase standard that converts phase variations into recorded intensity fringe modulations.",
    "correctIndex": 3,
    "hintEn": "Because detectors only register intensity |E|^2, interfering with a coherent reference beam encodes the phase through cross-terms.",
    "hintAr": "نظراً لأن الألواح الحساسة تسجل الشدة فقط |E|^2، فإن التداخل مع حزمة مرجعية معلومة الطور يشفر معلومات الطور كأهداب تداخل.",
    "stepByStepSolutionEn": [
      "1. Holographic emulsion records only irradiance $I = |E_O + E_R|^2 = |E_O|^2 + |E_R|^2 + 2 |E_O||E_R| \\cos(\\phi_O - \\phi_R)$.",
      "2. The interference cross-term encodes the phase $\\phi_O$ as spatial fringe spacing."
    ],
    "stepByStepSolutionAr": [
      "١. يسجل اللوح الحساس الشدة الكلية: $I = |E_O|^2 + |E_R|^2 + 2 |E_O||E_R| \\cos(\\phi_O - \\phi_R)$.",
      "٢. يحتوي حد التداخل على فرق الطور $(\\phi_O - \\phi_R)$ في صورة أهداب تداخل مجهرية تحفظ عمق الجسم."
    ],
    "teacherTipEn": "Without a coherent reference beam, optical phase information is completely lost.",
    "teacherTipAr": "بدون الحزمة المرجعية المترابطة، تُفقد معلومات الطور وعمق التضاريس ثلاثية الأبعاد تماماً."
  },
  {
    "id": "egbac_phys_ch3_ex_11",
    "titleEn": "Three-Level vs Four-Level Laser Systems",
    "titleAr": "مقارنة بين منظومات الليزر ثلاثية المستويات ورباعية المستويات",
    "difficulty": "medium",
    "questionEn": "Why are four-level laser systems (such as the He-Ne and Nd:YAG lasers) far more energy-efficient than three-level systems (such as the Ruby laser)?",
    "questionAr": "لماذا تُعد منظومات الليزر رباعية المستويات (مثل ليزر He-Ne وليزر Nd:YAG) أكثر كفاءة في استهلاك الطاقة من المنظومات ثلاثية المستويات (مثل ليزر الياقوت)؟",
    "optionsEn": [
      "The lower laser level is an excited state that depopulates rapidly, requiring far lower pumping power to establish inversion.",
      "Four-level systems produce four different colors of light at the same time.",
      "Four-level systems operate without mirrors or optical resonant cavities.",
      "Three-level systems cannot use optical pumping."
    ],
    "optionsAr": [
      "مستوى الليزر الأدنى هو مستوى مثار يفرغ سريعاً، مما يتطلب طاقة ضخ أقل بكثير لتحقيق الإسكان المعكوس.",
      "تنتج المنظومة رباعية المستويات أربعة ألوان مختلفة في نفس اللحظة.",
      "تعمل المنظومة رباعية المستويات بدون مرايا أو تجاويف رنينية.",
      "لا يمكن لمنظومة المستويات الثلاثة استخدام الضخ الضوئي."
    ],
    "correctAnswer": "The lower laser level is an excited state that depopulates rapidly, requiring far lower pumping power to establish inversion.",
    "correctIndex": 0,
    "hintEn": "In a 3-level laser, the lower laser level is the ground state, so >50% of ALL atoms must be pumped to invert the population. In 4-level systems, the lower laser level is almost empty.",
    "hintAr": "في ليزر المستويات الثلاثة، المستوى الأدنى هو المستوى الأرضي، لذا يجب إثارة أكثر من 50% من جميع الذرات. بينما في المنظومة الرباعية يكون المستوى الأدنى شبه فارغ بطبيعته.",
    "stepByStepSolutionEn": [
      "1. In 3-level systems (Ruby), the lower laser level is the ground state ($E_1$). Population inversion requires pumping more than half of all atoms ($N_2 > N_{\\text{total}}/2$).",
      "2. In 4-level systems (Nd:YAG, He-Ne), the lower laser level ($E_2$) is an excited level above ground that decays almost instantaneously, so $N_2 \\approx 0$. Thus, even a small population in $E_3$ easily establishes $N_3 > N_2$."
    ],
    "stepByStepSolutionAr": [
      "١. في المنظومة الثلاثية (الياقوت): المستوى الأدنى هو المستوى الأرضي الممتلئ تماماً، فيلزم إثارة أكثر من 50% من جميع ذرات الوسط لتحقيق الإسكان المعكوس.",
      "٢. في المنظومة الرباعية: المستوى الأدنى هو مستوى إثارة سريع التفريغ وشبه فارغ دائماً ($N_2 \\approx 0$)، فيكفي عدد ضئيل من الذرات في المستوى الثالث لتحقيق $N_3 > N_2$."
    ],
    "teacherTipEn": "This makes continuous-wave (CW) operation simple in 4-level lasers, whereas 3-level lasers typically require intense pulsed pumping.",
    "teacherTipAr": "لهذا تعمل ليزرات المنظومة الرباعية بنمط مستمر بسهولة، بينما تتطلب ليزرات المنظومة الثلاثية نبضات ضخ مكثفة."
  },
  {
    "id": "egbac_phys_ch3_ex_12",
    "titleEn": "Comparison of Optical Pumping vs Electrical Discharge Pumping",
    "titleAr": "مقارنة بين الضخ الضوئي والضخ بالتفريغ الكهربي",
    "difficulty": "easy",
    "questionEn": "Which pumping mechanism is correctly matched with its typical laser system?",
    "questionAr": "أي من آليات الضخ التالية مقترنة بنوع الليزر المناسب لها فيزيائياً؟",
    "optionsEn": [
      "Optical pumping: Gas lasers; Electrical discharge: Liquid dye lasers.",
      "Optical pumping: Solid-state lasers (Ruby, Nd:YAG); Electrical discharge: Gas lasers (He-Ne, $\\text{CO}_2$).",
      "Chemical pumping: Semiconductor lasers; Optical pumping: Excimer gas lasers.",
      "Electrical discharge: Ruby crystal lasers; Optical pumping: He-Ne gas lasers."
    ],
    "optionsAr": [
      "الضخ الضوئي: ليزرات الغاز؛ التفريغ الكهربي: ليزرات الصبغة السائلة.",
      "الضخ الضوئي: ليزرات الحالة الصلبة (الياقوت، Nd:YAG)؛ التفريغ الكهربي: ليزرات الغاز (He-Ne، ثاني أكسيد الكربون).",
      "الضخ الكيميائي: ليزرات أشباه الموصلات؛ الضخ الضوئي: ليزرات الإكسيمر.",
      "التفريغ الكهربي: ليزر بلورة الياقوت؛ الضخ الضوئي: ليزر الهيليوم - نيون."
    ],
    "correctAnswer": "Optical pumping: Solid-state lasers (Ruby, Nd:YAG); Electrical discharge: Gas lasers (He-Ne, $\\text{CO}_2$).",
    "correctIndex": 1,
    "hintEn": "Solid crystals cannot conduct gas discharges, so they use intense flashlamps (optical pumping). Gases readily conduct discharges via ionization.",
    "hintAr": "البلورات الصلبة لا توصل تفريغاً غازياً وتستخدم ومضات ضوئية مكثفة (ضخ ضوئي)، بينما الغازات يسهل تأيينها بالتفريغ الكهربي.",
    "stepByStepSolutionEn": [
      "1. Solid-state ruby and Nd:YAG lasers use xenon flashlamps or diode laser arrays for optical pumping.",
      "2. Gas lasers like He-Ne and CO2 use high-voltage electrical discharges to generate energetic electrons that collide with gas atoms."
    ],
    "stepByStepSolutionAr": [
      "١. ليزرات الحالة الصلبة كالالياقوت تستخدم ومضات ضوئية مكثفة من مصابيح الزينون أو دايودات الليزر (ضخ ضوئي).",
      "٢. ليزرات الغاز كالهيليوم نيون وثاني أكسيد الكربون تستخدم فرق جهد كهربائي عالي لإحداث تفريغ كهربي يُثير الغاز."
    ],
    "teacherTipEn": "Semiconductor diode lasers use direct injection of electric current across the p-n junction.",
    "teacherTipAr": "بينما تستخدم دايودات أشباه الموصلات الحقن المباشر للتيار الكهربائي عبر الوصلة الثنائية."
  },
  {
    "id": "egbac_phys_ch3_ex_13",
    "titleEn": "Radiation Pressure from a Collimated Laser Beam",
    "titleAr": "الضغط الإشعاعي لشعاع ليزر متوازي",
    "difficulty": "medium",
    "questionEn": "A perfectly collimated laser beam of intensity $I = 3.0 \\times 10^5\\text{ W/m}^2$ strikes a totally absorbing target at normal incidence. What radiation pressure $P_{\\text{rad}}$ does the beam exert on the surface?",
    "questionAr": "يسقط شعاع ليزر متوازي تماماً شدته $I = 3.0 \\times 10^5\\text{ واط/م}^2$ عمودياً على هدف تام الامتصاص. ما الضغط الإشعاعي $P_{\\text{rad}}$ الذي يؤثر به الشعاع على سطح الهدف؟",
    "optionsEn": [
      "$2.0 \\times 10^{-3}\\text{ N/m}^2$",
      "$5.0 \\times 10^{-4}\\text{ N/m}^2$",
      "$1.0 \\times 10^{-3}\\text{ N/m}^2 \\; (1.0\\text{ mPa})$",
      "$3.0 \\times 10^{-1}\\text{ N/m}^2$"
    ],
    "optionsAr": [
      "$2.0 \\times 10^{-3}\\text{ نيوتن/م}^2$",
      "$5.0 \\times 10^{-4}\\text{ نيوتن/م}^2$",
      "$1.0 \\times 10^{-3}\\text{ نيوتن/م}^2 \\; (1.0\\text{ مللي باسكال})$",
      "$3.0 \\times 10^{-1}\\text{ نيوتن/م}^2$"
    ],
    "correctAnswer": "$1.0 \\times 10^{-3}\\text{ N/m}^2 \\; (1.0\\text{ mPa})$",
    "correctIndex": 2,
    "hintEn": "For total absorption, radiation pressure is P_rad = I / c.",
    "hintAr": "في حالة الامتصاص التام، يُعطى الضغط الإشعاعي بالعلاقة P_rad = I / c.",
    "stepByStepSolutionEn": [
      "1. Radiation pressure for total absorption: $P_{\\text{rad}} = \\frac{I}{c}$.",
      "2. Substitute values: $P_{\\text{rad}} = \\frac{3.0 \\times 10^5\\text{ W/m}^2}{3.0 \\times 10^8\\text{ m/s}} = 1.0 \\times 10^{-3}\\text{ N/m}^2 = 1.0\\text{ mPa}$."
    ],
    "stepByStepSolutionAr": [
      "١. الضغط الإشعاعي للسطح الممتص: $P_{\\text{rad}} = \\frac{I}{c}$.",
      "٢. الحساب: $P_{\\text{rad}} = \\frac{3.0 \\times 10^5}{3.0 \\times 10^8} = 1.0 \\times 10^{-3}\\text{ نيوتن/م}^2$."
    ],
    "teacherTipEn": "This radiation pressure is exploited in optical tweezers to hold and manipulate living biological cells non-invasively.",
    "teacherTipAr": "يُستغل هذا الضغط الإشعاعي في الملاقط الضوئية لاحتجاز الخلايا الحية والبكتيريا وتحريكها بدقة دون جراحة."
  },
  {
    "id": "egbac_phys_ch3_ex_14",
    "titleEn": "Cavity Length for 250 MHz Mode Spacing",
    "titleAr": "طول التجويف البصري اللازم لتباعد ترددي 250 ميجاهرتز بين الأنماط",
    "difficulty": "medium",
    "questionEn": "An optical engineer designs a gas laser cavity requiring a longitudinal mode frequency spacing of exactly $\\Delta\\nu = 250\\text{ MHz} = 2.5 \\times 10^8\\text{ Hz}$. What mirror separation distance $L$ must be chosen?",
    "questionAr": "يصمم مهندس بصريات تجويف ليزر غازي يشترط تباعداً ترددياً بين أنماطه الطولية مقداره $\\Delta\\nu = 250\\text{ ميجاهرتز} = 2.5 \\times 10^8\\text{ هرتز}$. ما المسافة الفاصلة $L$ بين المرآتين التي يجب اختيارها؟",
    "optionsEn": [
      "$L = 0.30\\text{ m}$",
      "$L = 1.20\\text{ m}$",
      "$L = 0.75\\text{ m}$",
      "$L = 0.60\\text{ m} \\; (60\\text{ cm})$"
    ],
    "optionsAr": [
      "$L = 0.30\\text{ م}$",
      "$L = 1.20\\text{ م}$",
      "$L = 0.75\\text{ م}$",
      "$L = 0.60\\text{ م} \\; (60\\text{ سم})$"
    ],
    "correctAnswer": "$L = 0.60\\text{ m} \\; (60\\text{ cm})$",
    "correctIndex": 3,
    "hintEn": "Formula: Delta nu = c / (2L) implies L = c / (2 * Delta nu).",
    "hintAr": "القانون: Delta nu = c / (2L) ومنه L = c / (2 * Delta nu).",
    "stepByStepSolutionEn": [
      "1. Mode separation formula: $\\Delta\\nu = \\frac{c}{2L} \\implies L = \\frac{c}{2\\Delta\\nu}$.",
      "2. Substitute constants: $L = \\frac{3.0 \\times 10^8\\text{ m/s}}{2 \\times (2.5 \\times 10^8\\text{ Hz})} = \\frac{3.0}{5.0} = 0.60\\text{ m} = 60\\text{ cm}$."
    ],
    "stepByStepSolutionAr": [
      "١. قانون التباعد الترددي: $L = \\frac{c}{2\\Delta\\nu}$.",
      "٢. الحساب: $L = \\frac{3.0 \\times 10^8}{2 \\times 2.5 \\times 10^8} = 0.60\\text{ م} = 60\\text{ سم}$."
    ],
    "teacherTipEn": "Precise piezoelectric transducers maintain cavity length L within fractions of a nanometer against thermal drift.",
    "teacherTipAr": "تُثبت محولات كهرضغطية دقيقة المسافة L بدقة كسر من النانومتر لمنع الانجراف الحراري للترددات."
  },
  {
    "id": "egbac_phys_ch3_ex_15",
    "titleEn": "Laser Altimetry and Lunar Laser Ranging",
    "titleAr": "قياس المدى بالليزر وارتفاعات تضاريس القمر",
    "difficulty": "easy",
    "questionEn": "In Lunar Laser Ranging (LLR), short laser pulses are fired from Earth at retroreflectors on the Moon, returning after round-trip time $\\Delta t = 2.56\\text{ s}$. Given $c = 3.0 \\times 10^8\\text{ m/s}$, calculate the one-way distance to the Moon.",
    "questionAr": "في تجارب قياس المدى القمري بالليزر، تُطلق نبضات ليزرية قصيرة من الأرض نحو عواكس مثبتة على سطح القمر، وتعود للأرض بعد زمن ذهاب وإياب $\\Delta t = 2.56\\text{ ثانية}$. بمعلومية سرعة الضوء $c = 3.0 \\times 10^8\\text{ م/ث}$، احسب المسافة إلى القمر.",
    "optionsEn": [
      "$384,000\\text{ km} \\; (3.84 \\times 10^8\\text{ m})$",
      "$768,000\\text{ km}$",
      "$192,000\\text{ km}$",
      "$420,000\\text{ km}$"
    ],
    "optionsAr": [
      "$384,000\\text{ كم} \\; (3.84 \\times 10^8\\text{ م})$",
      "$768,000\\text{ كم}$",
      "$192,000\\text{ كم}$",
      "$420,000\\text{ كم}$"
    ],
    "correctAnswer": "$384,000\\text{ km} \\; (3.84 \\times 10^8\\text{ m})$",
    "correctIndex": 0,
    "hintEn": "Distance is d = c * (Delta t / 2).",
    "hintAr": "المسافة d = c * (Delta t / 2).",
    "stepByStepSolutionEn": [
      "1. Round-trip distance is $2d = c \\cdot \\Delta t$.",
      "2. One-way distance: $d = \\frac{c \\cdot \\Delta t}{2} = \\frac{(3.0 \\times 10^8\\text{ m/s})(2.56\\text{ s})}{2} = 3.84 \\times 10^8\\text{ m} = 384,000\\text{ km}$."
    ],
    "stepByStepSolutionAr": [
      "١. مسافة الذهاب والإياب: $2d = c \\cdot \\Delta t$.",
      "٢. المسافة باتجاه واحد: $d = \\frac{3.0 \\times 10^8 \\times 2.56}{2} = 3.84 \\times 10^8\\text{ م} = 384000\\text{ كم}$."
    ],
    "teacherTipEn": "This laser technique measures Earth-Moon distance with sub-millimeter precision, tracking lunar orbit recession (~3.8 cm/year).",
    "teacherTipAr": "تقيس هذه التقنية المسافة بين الأرض والقمر بدقة أجزاء من المليمتر، متتبعة ابتعاد مدار القمر بمقدار 3.8 سم سنوياً."
  }
];
